/* SPDX-License-Identifier: GPL-3.0-or-later
 *
 * NUT's per-vendor variable tables, as data (ups_vartab.c, generated by
 * tools/gen-vartab.py from NUT's usbhid-ups subdrivers).
 *
 * A row says: this NUT variable comes from this HID path, converted this
 * way. A UPS gets the list for the NUT subdriver that claims its USB ID (or
 * the rows two or more subdrivers agree on, for one none claims), and at
 * enumeration each row is matched against the UPS's own descriptor by exact
 * path. Where a variable has several rows (battery.voltage from
 * UPS.Battery.Voltage, else UPS.PowerSummary.Voltage), the first one the UPS
 * actually has wins, exactly as in NUT.
 */
#ifndef UPSA_UPS_VARTAB_H
#define UPSA_UPS_VARTAB_H

#include <stddef.h>
#include <stdint.h>

typedef enum {
    VCONV_NONE,      /* the value as scaled, printed with `decimals` */
    VCONV_BEEPER,    /* 1 disabled, 2 enabled, 3 muted */
    VCONV_TEST,      /* self-test result words */
    VCONV_YESNO,     /* 0 no, 1 yes */
    VCONV_ONOFF,     /* 0 off, 1 on */
    VCONV_DATE,      /* HID packed date -> YYYY/MM/DD */
    VCONV_KELVIN,    /* 273..373 is Kelvin -> Celsius, else already Celsius */
    VCONV_DIV10,
    VCONV_DIV100,
    VCONV_STRINGID,  /* the value is a USB string descriptor index */
    VCONV_HEX,
    /* cps-hid.c, ported in ups_vars.c; the scale corrections only on
     * CyberPower 0764:0501, where NUT enables them. */
    VCONV_CPS_BATTVOLT,   /* x2/3 when the first reading is > 1.4x nominal */
    VCONV_CPS_BATTCHARGE, /* clamped to 100 */
    VCONV_CPS_INFREQ,     /* x0.1 when it reads in tenths of a hertz */
    VCONV_CPS_OUTFREQ,
} ups_vconv_t;

/* How often NUT reads it: every poll, now and then, or once at enumeration. */
enum { VPOLL_NORMAL = 0, VPOLL_SEMI = 1, VPOLL_STATIC = 2 };

#define UPS_VARTAB_MAX_NODES 11   /* HID_PATH_MAX_DEPTH + the field's usage */

typedef struct {
    const char *name;             /* NUT variable */
    uint8_t     conv;             /* ups_vconv_t */
    uint8_t     decimals;
    uint8_t     poll;             /* VPOLL_* */
    uint8_t     depth;            /* nodes used, the last is the field's usage */
    uint32_t    node[UPS_VARTAB_MAX_NODES];
} ups_vartab_row_t;

typedef struct { const char *name; int index; } ups_vartab_sub_t;
typedef struct { uint16_t vid, pid; int sub; } ups_vartab_id_t;

extern const ups_vartab_row_t ups_vartab_rows[];
extern const size_t           ups_vartab_row_count;
extern const ups_vartab_sub_t ups_vartab_subs[];
extern const size_t           ups_vartab_sub_count;
extern const ups_vartab_id_t  ups_vartab_ids[];
extern const size_t           ups_vartab_id_count;

/* Vendor-page usages (page >= 0xFF00) that some row reads, sorted. The
 * parser keeps fields on exactly these and drops the rest of a vendor page. */
extern const uint32_t ups_vartab_vendor_usages[];
extern const size_t   ups_vartab_vendor_usage_count;

/* NUT's status collectors ("BOOL" rows): a HID path whose value, through one
 * of NUT's lookups, sets or clears a status token (ups_nutstatus.h). */
typedef struct { int32_t value; uint8_t token; uint8_t clear; } ups_st_lkp_t;
/* A lookup entry with this value is NUT's "value ? tok : !tok" (Liebert):
 * any non-zero value sets the token, zero clears it. */
#define UPS_ST_NONZERO INT32_MIN
typedef struct {
    const ups_st_lkp_t *lk;
    uint8_t             nlk;
    uint8_t             depth;
    uint32_t            node[UPS_VARTAB_MAX_NODES];
} ups_st_row_t;
extern const ups_st_row_t ups_st_rows[];
/* The ordered status row list for subdriver `sub`, or the common one for -1. */
const uint16_t *ups_st_list(int sub, size_t *len);

/* The ordered row list for subdriver `sub`, or the common list for -1. */
const uint16_t *ups_vartab_list(int sub, size_t *len);

#endif
