/* SPDX-License-Identifier: GPL-3.0-or-later
 *
 * GENERATED by tools/gen-vartab.py from NUT 3154ca0 2026-09-23. Do not edit:
 * change the generator, or NUT, and regenerate.
 *
 * NUT (networkupstools.org) is GPL-2.0-or-later; its usbhid-ups tables are
 * the source of every row here. */
#include "ups_vartab.h"

const ups_vartab_row_t ups_vartab_rows[405] = {
    { "device.usb.version", VCONV_STRINGID, 0, 2, 4, { 0x00840004, 0xffff00e5, 0xffff0005, 0xffff00f1 } },
    { "battery.charge", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00840024, 0x00850066 } },
    { "battery.charge.low", VCONV_NONE, 0, 1, 3, { 0x00840004, 0x00840024, 0xffff004d } },
    { "battery.charge.low", VCONV_NONE, 0, 2, 3, { 0x00840004, 0x00840024, 0x00850029 } },
    { "battery.charge.restart", VCONV_NONE, 0, 1, 3, { 0x00840004, 0x00840024, 0xffff005f } },
    { "battery.runtime", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00840024, 0x00850068 } },
    { "battery.runtime.low", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00840024, 0x0085002a } },
    { "battery.runtime.elapsed", VCONV_NONE, 0, 0, 7, { 0x00840004, 0xffff0004, 0x0084001a, 0x00ff0001, 0xffff0003, 0x00ff0001, 0xffff0097 } },
    { "battery.temperature", VCONV_KELVIN, 0, 0, 4, { 0x00840004, 0x00840010, 0x00840012, 0x00840036 } },
    { "battery.type", VCONV_STRINGID, 0, 2, 3, { 0x00840004, 0x00840024, 0x00850089 } },
    { "battery.voltage", VCONV_NONE, 1, 0, 3, { 0x00840004, 0x00840010, 0x00840030 } },
    { "battery.voltage.nominal", VCONV_NONE, 0, 2, 3, { 0x00840004, 0x00840010, 0x00840040 } },
    { "battery.protection", VCONV_YESNO, 0, 1, 4, { 0x00840004, 0x00840010, 0x00840012, 0xffff0049 } },
    { "battery.energysave", VCONV_YESNO, 0, 1, 5, { 0x00840004, 0x00840016, 0x0084001a, 0x00ff0003, 0xffff0046 } },
    { "battery.energysave.load", VCONV_NONE, 0, 1, 5, { 0x00840004, 0x00840016, 0x0084001a, 0x00ff0003, 0x00840045 } },
    { "battery.energysave.delay", VCONV_NONE, 0, 1, 6, { 0x00840004, 0x00840016, 0x0084001a, 0x00ff0003, 0xffff0046, 0xffff005d } },
    { "battery.energysave.delay", VCONV_NONE, 0, 1, 5, { 0x00840004, 0x00840016, 0x0084001a, 0x00ff0003, 0xffff005d } },
    { "battery.energysave.realpower", VCONV_NONE, 0, 1, 5, { 0x00840004, 0x00840016, 0x0084001a, 0x00ff0003, 0x00840044 } },
    { "ups.efficiency", VCONV_NONE, 0, 0, 4, { 0x00840004, 0x00840016, 0x0084001c, 0xffff0086 } },
    { "ups.firmware", VCONV_STRINGID, 0, 2, 3, { 0x00840004, 0x00840024, 0xffff00f1 } },
    { "ups.load", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00840024, 0x00840035 } },
    { "ups.load.high", VCONV_NONE, 0, 1, 4, { 0x00840004, 0x0084001e, 0x00ff0004, 0x00840045 } },
    { "ups.timer.start", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00840024, 0x00840056 } },
    { "ups.timer.shutdown", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00840024, 0x00840057 } },
    { "ups.timer.reboot", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00840024, 0x00840055 } },
    { "ups.test.result", VCONV_TEST, 0, 0, 4, { 0x00840004, 0x00840010, 0x00840012, 0x00840058 } },
    { "ups.test.interval", VCONV_NONE, 0, 1, 4, { 0x00840004, 0x00840010, 0x00840012, 0xffff0045 } },
    { "ups.beeper.status", VCONV_BEEPER, 0, 1, 4, { 0x00840004, 0x00840010, 0x00840012, 0x0084005a } },
    { "ups.beeper.status", VCONV_BEEPER, 0, 1, 3, { 0x00840004, 0x00840024, 0x0084005a } },
    { "ups.beeper.status", VCONV_BEEPER, 0, 1, 2, { 0x00840004, 0x0084005a } },
    { "ups.temperature", VCONV_KELVIN, 0, 0, 3, { 0x00840004, 0x00840024, 0x00840036 } },
    { "ups.power", VCONV_NONE, 0, 0, 4, { 0x00840004, 0x00840016, 0x0084001c, 0x00840033 } },
    { "ups.L1.power", VCONV_NONE, 0, 0, 6, { 0x00840004, 0x00840016, 0x0084001c, 0xffff0010, 0x00ff0001, 0x00840033 } },
    { "ups.L2.power", VCONV_NONE, 0, 0, 6, { 0x00840004, 0x00840016, 0x0084001c, 0xffff0010, 0x00ff0002, 0x00840033 } },
    { "ups.L3.power", VCONV_NONE, 0, 0, 6, { 0x00840004, 0x00840016, 0x0084001c, 0xffff0010, 0x00ff0003, 0x00840033 } },
    { "ups.power.nominal", VCONV_NONE, 0, 2, 4, { 0x00840004, 0x0084001e, 0x00ff0004, 0x00840043 } },
    { "ups.realpower", VCONV_NONE, 0, 0, 4, { 0x00840004, 0x00840016, 0x0084001c, 0x00840034 } },
    { "ups.L1.realpower", VCONV_NONE, 0, 0, 6, { 0x00840004, 0x00840016, 0x0084001c, 0xffff0010, 0x00ff0001, 0x00840034 } },
    { "ups.L2.realpower", VCONV_NONE, 0, 0, 6, { 0x00840004, 0x00840016, 0x0084001c, 0xffff0010, 0x00ff0002, 0x00840034 } },
    { "ups.L3.realpower", VCONV_NONE, 0, 0, 6, { 0x00840004, 0x00840016, 0x0084001c, 0xffff0010, 0x00ff0003, 0x00840034 } },
    { "ups.realpower.nominal", VCONV_NONE, 0, 2, 4, { 0x00840004, 0x0084001e, 0x00ff0004, 0x00840044 } },
    { "ups.start.auto", VCONV_YESNO, 0, 1, 5, { 0x00840004, 0x00840016, 0x0084001a, 0x00ff0001, 0xffff0043 } },
    { "ups.start.battery", VCONV_YESNO, 0, 1, 5, { 0x00840004, 0x00840016, 0x0084001a, 0x00ff0003, 0xffff0047 } },
    { "ups.start.reboot", VCONV_YESNO, 0, 1, 4, { 0x00840004, 0x00840016, 0x0084001c, 0xffff0044 } },
    { "input.voltage", VCONV_NONE, 1, 0, 5, { 0x00840004, 0x00840016, 0x0084001a, 0x00ff0001, 0x00840030 } },
    { "input.L1-N.voltage", VCONV_NONE, 1, 0, 7, { 0x00840004, 0x00840016, 0x0084001a, 0x00ff0001, 0xffff0010, 0x00ff0001, 0x00840030 } },
    { "input.L2-N.voltage", VCONV_NONE, 1, 0, 7, { 0x00840004, 0x00840016, 0x0084001a, 0x00ff0001, 0xffff0010, 0x00ff0002, 0x00840030 } },
    { "input.L3-N.voltage", VCONV_NONE, 1, 0, 7, { 0x00840004, 0x00840016, 0x0084001a, 0x00ff0001, 0xffff0010, 0x00ff0003, 0x00840030 } },
    { "input.L1-L2.voltage", VCONV_NONE, 1, 0, 7, { 0x00840004, 0x00840016, 0x0084001a, 0x00ff0001, 0xffff0010, 0x00ff000c, 0x00840030 } },
    { "input.L2-L3.voltage", VCONV_NONE, 1, 0, 7, { 0x00840004, 0x00840016, 0x0084001a, 0x00ff0001, 0xffff0010, 0x00ff0017, 0x00840030 } },
    { "input.L3-L1.voltage", VCONV_NONE, 1, 0, 7, { 0x00840004, 0x00840016, 0x0084001a, 0x00ff0001, 0xffff0010, 0x00ff001f, 0x00840030 } },
    { "input.voltage.nominal", VCONV_NONE, 0, 2, 4, { 0x00840004, 0x0084001e, 0x00ff0001, 0x00840040 } },
    { "input.current", VCONV_NONE, 2, 0, 5, { 0x00840004, 0x00840016, 0x0084001a, 0x00ff0001, 0x00840031 } },
    { "input.L1.current", VCONV_NONE, 1, 0, 7, { 0x00840004, 0x00840016, 0x0084001a, 0x00ff0001, 0xffff0010, 0x00ff0001, 0x00840031 } },
    { "input.L2.current", VCONV_NONE, 1, 0, 7, { 0x00840004, 0x00840016, 0x0084001a, 0x00ff0001, 0xffff0010, 0x00ff0002, 0x00840031 } },
    { "input.L3.current", VCONV_NONE, 1, 0, 7, { 0x00840004, 0x00840016, 0x0084001a, 0x00ff0001, 0xffff0010, 0x00ff0003, 0x00840031 } },
    { "input.current.nominal", VCONV_NONE, 2, 2, 4, { 0x00840004, 0x0084001e, 0x00ff0001, 0x00840041 } },
    { "input.frequency", VCONV_NONE, 1, 0, 5, { 0x00840004, 0x00840016, 0x0084001a, 0x00ff0001, 0x00840032 } },
    { "input.frequency.nominal", VCONV_NONE, 0, 2, 4, { 0x00840004, 0x0084001e, 0x00ff0001, 0x00840042 } },
    { "input.transfer.low", VCONV_NONE, 0, 1, 4, { 0x00840004, 0x00840016, 0x0084001c, 0x00840053 } },
    { "input.transfer.eco.low", VCONV_NONE, 0, 1, 4, { 0x00840004, 0x00840016, 0x0084001c, 0xffff005a } },
    { "input.transfer.bypass.low", VCONV_NONE, 0, 1, 4, { 0x00840004, 0x00840016, 0x0084001c, 0xffff0057 } },
    { "input.transfer.boost.low", VCONV_NONE, 0, 1, 4, { 0x00840004, 0x00840016, 0x0084001c, 0xffff0050 } },
    { "input.transfer.boost.high", VCONV_NONE, 0, 1, 4, { 0x00840004, 0x00840016, 0x0084001c, 0xffff0051 } },
    { "input.transfer.trim.low", VCONV_NONE, 0, 1, 4, { 0x00840004, 0x00840016, 0x0084001c, 0xffff0052 } },
    { "input.transfer.high", VCONV_NONE, 0, 1, 4, { 0x00840004, 0x00840016, 0x0084001c, 0x00840054 } },
    { "input.transfer.eco.high", VCONV_NONE, 0, 1, 4, { 0x00840004, 0x00840016, 0x0084001c, 0xffff005b } },
    { "input.transfer.bypass.high", VCONV_NONE, 0, 1, 4, { 0x00840004, 0x00840016, 0x0084001c, 0xffff0058 } },
    { "input.transfer.frequency.bypass.range", VCONV_NONE, 0, 1, 4, { 0x00840004, 0x00840016, 0x0084001c, 0xffff0059 } },
    { "input.transfer.frequency.eco.range", VCONV_NONE, 0, 1, 4, { 0x00840004, 0x00840016, 0x0084001c, 0xffff005c } },
    { "input.transfer.hysteresis", VCONV_NONE, 0, 1, 4, { 0x00840004, 0x00840016, 0x0084001c, 0xffff009c } },
    { "input.transfer.trim.high", VCONV_NONE, 0, 1, 4, { 0x00840004, 0x00840016, 0x0084001c, 0xffff0053 } },
    { "input.voltage.extended", VCONV_YESNO, 0, 1, 4, { 0x00840004, 0x00840016, 0x0084001c, 0xffff004b } },
    { "input.frequency.extended", VCONV_YESNO, 0, 1, 4, { 0x00840004, 0x00840016, 0x0084001c, 0xffff004e } },
    { "input.bypass.voltage", VCONV_NONE, 1, 0, 5, { 0x00840004, 0x00840016, 0x0084001a, 0x00ff0002, 0x00840030 } },
    { "input.bypass.L1-N.voltage", VCONV_NONE, 1, 0, 7, { 0x00840004, 0x00840016, 0x0084001a, 0x00ff0002, 0xffff0010, 0x00ff0001, 0x00840030 } },
    { "input.bypass.L2-N.voltage", VCONV_NONE, 1, 0, 7, { 0x00840004, 0x00840016, 0x0084001a, 0x00ff0002, 0xffff0010, 0x00ff0002, 0x00840030 } },
    { "input.bypass.L3-N.voltage", VCONV_NONE, 1, 0, 7, { 0x00840004, 0x00840016, 0x0084001a, 0x00ff0002, 0xffff0010, 0x00ff0003, 0x00840030 } },
    { "input.bypass.L1-L2.voltage", VCONV_NONE, 1, 0, 7, { 0x00840004, 0x00840016, 0x0084001a, 0x00ff0002, 0xffff0010, 0x00ff000c, 0x00840030 } },
    { "input.bypass.L2-L3.voltage", VCONV_NONE, 1, 0, 7, { 0x00840004, 0x00840016, 0x0084001a, 0x00ff0002, 0xffff0010, 0x00ff0017, 0x00840030 } },
    { "input.bypass.L3-L1.voltage", VCONV_NONE, 1, 0, 7, { 0x00840004, 0x00840016, 0x0084001a, 0x00ff0002, 0xffff0010, 0x00ff001f, 0x00840030 } },
    { "input.bypass.voltage.nominal", VCONV_NONE, 0, 2, 4, { 0x00840004, 0x0084001e, 0x00ff0002, 0x00840040 } },
    { "input.bypass.current", VCONV_NONE, 2, 0, 5, { 0x00840004, 0x00840016, 0x0084001a, 0x00ff0002, 0x00840031 } },
    { "input.bypass.L1.current", VCONV_NONE, 1, 0, 7, { 0x00840004, 0x00840016, 0x0084001a, 0x00ff0002, 0xffff0010, 0x00ff0001, 0x00840031 } },
    { "input.bypass.L2.current", VCONV_NONE, 1, 0, 7, { 0x00840004, 0x00840016, 0x0084001a, 0x00ff0002, 0xffff0010, 0x00ff0002, 0x00840031 } },
    { "input.bypass.L3.current", VCONV_NONE, 1, 0, 7, { 0x00840004, 0x00840016, 0x0084001a, 0x00ff0002, 0xffff0010, 0x00ff0003, 0x00840031 } },
    { "input.bypass.current.nominal", VCONV_NONE, 2, 2, 4, { 0x00840004, 0x0084001e, 0x00ff0002, 0x00840041 } },
    { "input.bypass.frequency", VCONV_NONE, 1, 0, 5, { 0x00840004, 0x00840016, 0x0084001a, 0x00ff0002, 0x00840032 } },
    { "input.bypass.frequency.nominal", VCONV_NONE, 0, 2, 4, { 0x00840004, 0x0084001e, 0x00ff0002, 0x00840042 } },
    { "output.voltage", VCONV_NONE, 1, 0, 4, { 0x00840004, 0x00840016, 0x0084001c, 0x00840030 } },
    { "output.L1-N.voltage", VCONV_NONE, 1, 0, 6, { 0x00840004, 0x00840016, 0x0084001c, 0xffff0010, 0x00ff0001, 0x00840030 } },
    { "output.L2-N.voltage", VCONV_NONE, 1, 0, 6, { 0x00840004, 0x00840016, 0x0084001c, 0xffff0010, 0x00ff0002, 0x00840030 } },
    { "output.L3-N.voltage", VCONV_NONE, 1, 0, 6, { 0x00840004, 0x00840016, 0x0084001c, 0xffff0010, 0x00ff0003, 0x00840030 } },
    { "output.L1-L2.voltage", VCONV_NONE, 1, 0, 6, { 0x00840004, 0x00840016, 0x0084001c, 0xffff0010, 0x00ff000c, 0x00840030 } },
    { "output.L2-L3.voltage", VCONV_NONE, 1, 0, 6, { 0x00840004, 0x00840016, 0x0084001c, 0xffff0010, 0x00ff0017, 0x00840030 } },
    { "output.L3-L1.voltage", VCONV_NONE, 1, 0, 6, { 0x00840004, 0x00840016, 0x0084001c, 0xffff0010, 0x00ff001f, 0x00840030 } },
    { "output.current", VCONV_NONE, 2, 0, 4, { 0x00840004, 0x00840016, 0x0084001c, 0x00840031 } },
    { "output.L1.current", VCONV_NONE, 1, 0, 6, { 0x00840004, 0x00840016, 0x0084001c, 0xffff0010, 0x00ff0001, 0x00840031 } },
    { "output.L2.current", VCONV_NONE, 1, 0, 6, { 0x00840004, 0x00840016, 0x0084001c, 0xffff0010, 0x00ff0002, 0x00840031 } },
    { "output.L3.current", VCONV_NONE, 1, 0, 6, { 0x00840004, 0x00840016, 0x0084001c, 0xffff0010, 0x00ff0003, 0x00840031 } },
    { "output.current.nominal", VCONV_NONE, 2, 0, 4, { 0x00840004, 0x0084001e, 0x00ff0004, 0x00840041 } },
    { "output.frequency", VCONV_NONE, 1, 0, 4, { 0x00840004, 0x00840016, 0x0084001c, 0x00840032 } },
    { "output.frequency.nominal", VCONV_NONE, 0, 2, 4, { 0x00840004, 0x0084001e, 0x00ff0004, 0x00840042 } },
    { "outlet.id", VCONV_NONE, 0, 2, 5, { 0x00840004, 0x00840018, 0x00840020, 0x00ff0001, 0x00840021 } },
    { "outlet.switchable", VCONV_YESNO, 0, 2, 6, { 0x00840004, 0x00840018, 0x00840020, 0x00ff0001, 0x00840002, 0x0084006c } },
    { "outlet.power", VCONV_NONE, 0, 0, 5, { 0x00840004, 0x00840018, 0x00840020, 0x00ff0001, 0x00840033 } },
    { "outlet.realpower", VCONV_NONE, 0, 0, 5, { 0x00840004, 0x00840018, 0x00840020, 0x00ff0001, 0x00840034 } },
    { "outlet.current", VCONV_NONE, 2, 0, 5, { 0x00840004, 0x00840018, 0x00840020, 0x00ff0001, 0x00840031 } },
    { "outlet.powerfactor", VCONV_NONE, 2, 0, 5, { 0x00840004, 0x00840018, 0x00840020, 0x00ff0001, 0xffff0069 } },
    { "outlet.1.id", VCONV_NONE, 0, 2, 5, { 0x00840004, 0x00840018, 0x00840020, 0x00ff0002, 0x00840021 } },
    { "outlet.1.switchable", VCONV_YESNO, 0, 2, 6, { 0x00840004, 0x00840018, 0x00840020, 0x00ff0002, 0x00840002, 0x0084006c } },
    { "outlet.1.status", VCONV_ONOFF, 0, 0, 6, { 0x00840004, 0x00840018, 0x00840020, 0x00ff0002, 0x00840002, 0x0084006b } },
    { "outlet.1.designator", VCONV_STRINGID, 0, 2, 5, { 0x00840004, 0x00840018, 0x00840020, 0x00ff0002, 0xffff00ba } },
    { "outlet.1.status", VCONV_ONOFF, 0, 0, 4, { 0x00840004, 0x00840024, 0x00840002, 0x008500d0 } },
    { "outlet.1.autoswitch.charge.low", VCONV_NONE, 0, 1, 5, { 0x00840004, 0x00840018, 0x00840020, 0x00ff0002, 0x00850029 } },
    { "outlet.1.delay.shutdown", VCONV_NONE, 0, 1, 5, { 0x00840004, 0x00840018, 0x00840020, 0x00ff0002, 0xffff005d } },
    { "outlet.1.delay.start", VCONV_NONE, 0, 1, 5, { 0x00840004, 0x00840018, 0x00840020, 0x00ff0002, 0xffff005e } },
    { "outlet.1.power", VCONV_NONE, 0, 0, 5, { 0x00840004, 0x00840018, 0x00840020, 0x00ff0002, 0x00840033 } },
    { "outlet.1.realpower", VCONV_NONE, 0, 0, 5, { 0x00840004, 0x00840018, 0x00840020, 0x00ff0002, 0x00840034 } },
    { "outlet.1.current", VCONV_NONE, 2, 0, 5, { 0x00840004, 0x00840018, 0x00840020, 0x00ff0002, 0x00840031 } },
    { "outlet.1.powerfactor", VCONV_NONE, 2, 0, 5, { 0x00840004, 0x00840018, 0x00840020, 0x00ff0002, 0xffff0069 } },
    { "outlet.2.id", VCONV_NONE, 0, 2, 5, { 0x00840004, 0x00840018, 0x00840020, 0x00ff0003, 0x00840021 } },
    { "outlet.2.switchable", VCONV_YESNO, 0, 0, 6, { 0x00840004, 0x00840018, 0x00840020, 0x00ff0003, 0x00840002, 0x0084006c } },
    { "outlet.2.status", VCONV_ONOFF, 0, 0, 6, { 0x00840004, 0x00840018, 0x00840020, 0x00ff0003, 0x00840002, 0x0084006b } },
    { "outlet.2.autoswitch.charge.low", VCONV_NONE, 0, 1, 5, { 0x00840004, 0x00840018, 0x00840020, 0x00ff0003, 0x00850029 } },
    { "outlet.2.delay.shutdown", VCONV_NONE, 0, 1, 5, { 0x00840004, 0x00840018, 0x00840020, 0x00ff0003, 0xffff005d } },
    { "outlet.2.delay.start", VCONV_NONE, 0, 1, 5, { 0x00840004, 0x00840018, 0x00840020, 0x00ff0003, 0xffff005e } },
    { "outlet.2.power", VCONV_NONE, 0, 0, 5, { 0x00840004, 0x00840018, 0x00840020, 0x00ff0003, 0x00840033 } },
    { "outlet.2.realpower", VCONV_NONE, 0, 0, 5, { 0x00840004, 0x00840018, 0x00840020, 0x00ff0003, 0x00840034 } },
    { "outlet.2.current", VCONV_NONE, 2, 0, 5, { 0x00840004, 0x00840018, 0x00840020, 0x00ff0003, 0x00840031 } },
    { "outlet.2.powerfactor", VCONV_NONE, 2, 0, 5, { 0x00840004, 0x00840018, 0x00840020, 0x00ff0003, 0xffff0069 } },
    { "outlet.3.id", VCONV_NONE, 0, 2, 5, { 0x00840004, 0x00840018, 0x00840020, 0x00ff0004, 0x00840021 } },
    { "outlet.3.switchable", VCONV_YESNO, 0, 0, 6, { 0x00840004, 0x00840018, 0x00840020, 0x00ff0004, 0x00840002, 0x0084006c } },
    { "outlet.3.status", VCONV_ONOFF, 0, 0, 6, { 0x00840004, 0x00840018, 0x00840020, 0x00ff0004, 0x00840002, 0x0084006b } },
    { "outlet.3.autoswitch.charge.low", VCONV_NONE, 0, 1, 5, { 0x00840004, 0x00840018, 0x00840020, 0x00ff0004, 0x00850029 } },
    { "outlet.3.delay.shutdown", VCONV_NONE, 0, 1, 5, { 0x00840004, 0x00840018, 0x00840020, 0x00ff0004, 0xffff005d } },
    { "outlet.3.delay.start", VCONV_NONE, 0, 1, 5, { 0x00840004, 0x00840018, 0x00840020, 0x00ff0004, 0xffff005e } },
    { "outlet.3.power", VCONV_NONE, 0, 0, 5, { 0x00840004, 0x00840018, 0x00840020, 0x00ff0004, 0x00840033 } },
    { "outlet.3.realpower", VCONV_NONE, 0, 0, 5, { 0x00840004, 0x00840018, 0x00840020, 0x00ff0004, 0x00840034 } },
    { "outlet.3.current", VCONV_NONE, 2, 0, 5, { 0x00840004, 0x00840018, 0x00840020, 0x00ff0004, 0x00840031 } },
    { "outlet.3.powerfactor", VCONV_NONE, 2, 0, 5, { 0x00840004, 0x00840018, 0x00840020, 0x00ff0004, 0xffff0069 } },
    { "battery.charge.low", VCONV_NONE, 0, 1, 3, { 0x00840004, 0x00840024, 0x00850029 } },
    { "battery.charge.warning", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00840024, 0x0085008c } },
    { "battery.runtime", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00840012, 0x00850068 } },
    { "battery.runtime.low", VCONV_NONE, 0, 1, 3, { 0x00840004, 0x00840012, 0x0085002a } },
    { "battery.runtime.low", VCONV_NONE, 0, 1, 3, { 0x00840004, 0x00840024, 0x0085002a } },
    { "battery.voltage", VCONV_NONE, 1, 0, 3, { 0x00840004, 0x00840012, 0x00840030 } },
    { "battery.voltage", VCONV_NONE, 1, 0, 3, { 0x00840004, 0x00840024, 0x00840030 } },
    { "battery.voltage.nominal", VCONV_NONE, 1, 0, 3, { 0x00840004, 0x00840012, 0x00840040 } },
    { "battery.voltage.nominal", VCONV_NONE, 1, 0, 3, { 0x00840004, 0x00840024, 0x00840040 } },
    { "battery.temperature", VCONV_KELVIN, 0, 0, 3, { 0x00840004, 0x00840012, 0x00840036 } },
    { "battery.type", VCONV_STRINGID, 0, 0, 3, { 0x00840004, 0x00840024, 0x00850089 } },
    { "battery.mfr.date", VCONV_DATE, 0, 1, 3, { 0x00840004, 0x00840012, 0x00850085 } },
    { "ups.load", VCONV_NONE, 1, 0, 3, { 0x00840004, 0x0084001c, 0x00840035 } },
    { "ups.load", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00840016, 0x00840035 } },
    { "ups.timer.start", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x0084001c, 0x00840056 } },
    { "ups.timer.shutdown", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x0084001c, 0x00840057 } },
    { "ups.timer.reboot", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x0084001c, 0x00840055 } },
    { "ups.timer.start", VCONV_NONE, 0, 0, 3, { 0x00840004, 0xff860005, 0xff86007e } },
    { "ups.timer.shutdown", VCONV_NONE, 0, 0, 3, { 0x00840004, 0xff860005, 0xff86007d } },
    { "ups.timer.reboot", VCONV_NONE, 0, 0, 3, { 0x00840004, 0xff860005, 0xff86007c } },
    { "ups.test.result", VCONV_TEST, 0, 0, 3, { 0x00840004, 0x00840012, 0x00840058 } },
    { "ups.beeper.status", VCONV_BEEPER, 0, 0, 3, { 0x00840004, 0x00840024, 0x0084005a } },
    { "ups.mfr.date", VCONV_DATE, 0, 0, 2, { 0x00840004, 0x00850085 } },
    { "ups.mfr.date", VCONV_DATE, 0, 0, 3, { 0x00840004, 0x00840024, 0x00850085 } },
    { "ups.realpower.nominal", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00840016, 0x00840044 } },
    { "ups.realpower.nominal", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x0084001c, 0x00840044 } },
    { "input.voltage", VCONV_NONE, 1, 0, 3, { 0x00840004, 0x0084001a, 0x00840030 } },
    { "input.voltage.nominal", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x0084001a, 0x00840040 } },
    { "input.transfer.low", VCONV_NONE, 0, 1, 3, { 0x00840004, 0x0084001c, 0x00840053 } },
    { "input.transfer.high", VCONV_NONE, 0, 1, 3, { 0x00840004, 0x0084001c, 0x00840054 } },
    { "input.transfer.low", VCONV_NONE, 0, 1, 3, { 0x00840004, 0x0084001a, 0x00840053 } },
    { "input.transfer.high", VCONV_NONE, 0, 1, 3, { 0x00840004, 0x0084001a, 0x00840054 } },
    { "output.voltage", VCONV_NONE, 1, 0, 3, { 0x00840004, 0x0084001c, 0x00840030 } },
    { "output.voltage.nominal", VCONV_NONE, 1, 0, 3, { 0x00840004, 0x0084001c, 0x00840040 } },
    { "output.current", VCONV_NONE, 2, 0, 3, { 0x00840004, 0x0084001c, 0x00840031 } },
    { "output.frequency", VCONV_NONE, 1, 0, 3, { 0x00840004, 0x0084001c, 0x00840032 } },
    { "ambient.temperature", VCONV_KELVIN, 0, 0, 4, { 0x00840004, 0xff860006, 0xff860007, 0x00840036 } },
    { "ambient.humidity", VCONV_NONE, 1, 0, 4, { 0x00840004, 0xff860006, 0xff860007, 0x00840037 } },
    { "battery.voltage.nominal", VCONV_NONE, 2, 0, 3, { 0x00840004, 0x00840024, 0x00840040 } },
    { "battery.voltage", VCONV_NONE, 2, 0, 3, { 0x00840004, 0x00840024, 0x00840030 } },
    { "battery.charge.warning", VCONV_NONE, 0, 1, 3, { 0x00840004, 0x00840024, 0x0085008c } },
    { "battery.charge", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00860010, 0x00860039 } },
    { "battery.charge.low", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00840024, 0x00850029 } },
    { "battery.voltage", VCONV_DIV10, 0, 0, 3, { 0x00840004, 0x00860010, 0x00860030 } },
    { "battery.voltage.nominal", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00860026, 0x00860044 } },
    { "input.frequency", VCONV_DIV10, 0, 0, 4, { 0x00840004, 0x0086002a, 0x0086001a, 0x00860032 } },
    { "input.frequency.nominal", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00860026, 0x00860042 } },
    { "input.transfer.high", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00860026, 0x00860054 } },
    { "input.transfer.high.max", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00860026, 0x0086005d } },
    { "input.transfer.high.min", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00860026, 0x0086005e } },
    { "input.transfer.low", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00860026, 0x00860053 } },
    { "input.transfer.low.max", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00860026, 0x0086005b } },
    { "input.transfer.low.min", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00860026, 0x0086005c } },
    { "input.voltage", VCONV_DIV10, 0, 0, 4, { 0x00840004, 0x0086002a, 0x0086001a, 0x00860030 } },
    { "input.voltage.nominal", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00860026, 0x00860040 } },
    { "output.frequency", VCONV_DIV10, 0, 0, 4, { 0x00840004, 0x0086002a, 0x0086001c, 0x00860032 } },
    { "output.voltage", VCONV_DIV10, 0, 0, 4, { 0x00840004, 0x0086002a, 0x0086001c, 0x00860030 } },
    { "ups.beeper.status", VCONV_BEEPER, 0, 0, 3, { 0x00840004, 0x00860027, 0x0086005a } },
    { "ups.timer.start", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00860027, 0x00860056 } },
    { "ups.timer.shutdown", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00860027, 0x00860057 } },
    { "ups.timer.reboot", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00860027, 0x00860055 } },
    { "ups.load", VCONV_NONE, 0, 0, 4, { 0x00840004, 0x0086002a, 0x0086001c, 0x00860035 } },
    { "ups.load.high", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00860026, 0x00860045 } },
    { "ups.power.nominal", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00860026, 0x00860043 } },
    { "ups.serial", VCONV_STRINGID, 0, 0, 3, { 0x00840004, 0x00840024, 0x008400ff } },
    { "input.frequency", VCONV_DIV10, 0, 0, 3, { 0x00840004, 0x0084001a, 0x00840032 } },
    { "ups.load", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x0084001c, 0x00840035 } },
    { "input.voltage.nominal", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x0084001e, 0x00840040 } },
    { "input.frequency", VCONV_DIV100, 0, 0, 4, { 0x00840004, 0x00840016, 0x0084001a, 0x00840032 } },
    { "output.voltage.nominal", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x0084001e, 0x00840040 } },
    { "output.frequency", VCONV_DIV100, 0, 0, 4, { 0x00840004, 0x00840016, 0x0084001c, 0x00840032 } },
    { "ups.load", VCONV_NONE, 0, 0, 4, { 0x00840004, 0x00840018, 0x00840020, 0x00840035 } },
    { "battery.voltage.nominal", VCONV_NONE, 0, 0, 4, { 0x00840004, 0x00840010, 0x00840012, 0x00840040 } },
    { "battery.capacity", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x0084001e, 0x00840043 } },
    { "battery.mfr.date", VCONV_STRINGID, 0, 0, 3, { 0x00840004, 0x00840024, 0x0085008f } },
    { "battery.voltage.nominal", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00840024, 0x00840040 } },
    { "ups.test.result", VCONV_TEST, 0, 0, 3, { 0x00840004, 0x0084001c, 0x00840058 } },
    { "ups.power", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x0084001c, 0x00840033 } },
    { "ups.power.nominal", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x0084001c, 0x00840043 } },
    { "ups.realpower", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x0084001c, 0x00840034 } },
    { "ups.firmware", VCONV_STRINGID, 0, 2, 3, { 0x00840004, 0x00840024, 0xff0100d0 } },
    { "output.voltage.nominal", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x0084001c, 0x00840040 } },
    { "input.voltage.nominal", VCONV_NONE, 1, 1, 4, { 0x00840004, 0x00840024, 0x0084001a, 0x00840040 } },
    { "input.voltage", VCONV_NONE, 1, 0, 4, { 0x00840004, 0x00840024, 0x0084001a, 0x00840030 } },
    { "input.voltage", VCONV_NONE, 1, 0, 4, { 0x00840004, 0x00840016, 0x0084001a, 0x00840030 } },
    { "input.transfer.low", VCONV_NONE, 1, 0, 4, { 0x00840004, 0x00840016, 0x0084001c, 0x00840053 } },
    { "input.transfer.high", VCONV_NONE, 1, 0, 4, { 0x00840004, 0x00840016, 0x0084001c, 0x00840054 } },
    { "input.transfer.low.min", VCONV_NONE, 1, 2, 4, { 0x00840004, 0x00840016, 0x0084001c, 0xffff0058 } },
    { "input.transfer.low.max", VCONV_NONE, 1, 2, 4, { 0x00840004, 0x00840016, 0x0084001c, 0xffff0057 } },
    { "input.transfer.high.min", VCONV_NONE, 1, 2, 4, { 0x00840004, 0x00840016, 0x0084001c, 0xffff005a } },
    { "input.transfer.high.max", VCONV_NONE, 1, 2, 4, { 0x00840004, 0x00840016, 0x0084001c, 0xffff0059 } },
    { "input.frequency", VCONV_NONE, 1, 0, 4, { 0x00840004, 0x00840016, 0x0084001a, 0x00840032 } },
    { "battery.voltage.nominal", VCONV_NONE, 1, 2, 4, { 0x00840004, 0x00840010, 0x00840012, 0x00840040 } },
    { "battery.voltage", VCONV_NONE, 1, 0, 4, { 0x00840004, 0x00840010, 0x00840012, 0x00840030 } },
    { "battery.charge", VCONV_NONE, 0, 0, 4, { 0x00840004, 0x00840010, 0x00840012, 0x00850066 } },
    { "battery.temperature", VCONV_KELVIN, 0, 0, 3, { 0x00840004, 0x00840010, 0x00840036 } },
    { "battery.capacity", VCONV_NONE, 0, 1, 3, { 0x00840004, 0x00840024, 0x00850083 } },
    { "battery.capacity", VCONV_NONE, 0, 1, 3, { 0x00840004, 0x00840024, 0x00850067 } },
    { "output.voltage.nominal", VCONV_NONE, 1, 1, 3, { 0x00840004, 0x0084001e, 0x00840040 } },
    { "output.frequency.nominal", VCONV_NONE, 1, 1, 3, { 0x00840004, 0x0084001e, 0x00840042 } },
    { "output.current", VCONV_NONE, 1, 0, 4, { 0x00840004, 0x00840016, 0x0084001c, 0x00840031 } },
    { "ups.test.result", VCONV_TEST, 0, 0, 3, { 0x00840004, 0x00840010, 0x00840058 } },
    { "ups.start.auto", VCONV_YESNO, 0, 0, 4, { 0x00840004, 0xffff0010, 0x00ff0001, 0xffff009c } },
    { "ups.power.nominal", VCONV_NONE, 0, 2, 3, { 0x00840004, 0x0084001e, 0x00840043 } },
    { "ups.realpower", VCONV_NONE, 1, 0, 4, { 0x00840004, 0x00840018, 0x00840020, 0x00840034 } },
    { "ups.realpower", VCONV_NONE, 1, 0, 4, { 0x00840004, 0x00840016, 0x0084001c, 0x00840034 } },
    { "ups.load", VCONV_NONE, 1, 0, 4, { 0x00840004, 0x00840018, 0x00840020, 0x00840035 } },
    { "ups.delay.start", VCONV_NONE, 0, 0, 4, { 0x00840004, 0x00840018, 0x00840020, 0xffff0081 } },
    { "ups.timer.start", VCONV_NONE, 0, 0, 4, { 0x00840004, 0x00840018, 0x00840020, 0x00840056 } },
    { "ups.timer.shutdown", VCONV_NONE, 0, 0, 4, { 0x00840004, 0x00840018, 0x00840020, 0x00840057 } },
    { "ups.timer.reboot", VCONV_NONE, 0, 0, 4, { 0x00840004, 0x00840018, 0x00840020, 0x00840055 } },
    { "ups.power.nominal", VCONV_NONE, 0, 2, 4, { 0x00840004, 0x0084001e, 0x00ff0004, 0x00840044 } },
    { "battery.voltage.nominal", VCONV_NONE, 1, 1, 3, { 0x00840004, 0x00840024, 0x00840040 } },
    { "battery.capacity.nominal", VCONV_NONE, 0, 1, 3, { 0x00840004, 0x00840024, 0x00850083 } },
    { "experimental.ups.powersummary.ioeminformation", VCONV_STRINGID, 0, 2, 3, { 0x00840004, 0x00840024, 0x0085008f } },
    { "experimental.ups.powersummary.presentstatus.shutdownrequested", VCONV_NONE, 0, 0, 4, { 0x00840004, 0x00840024, 0x00840002, 0x00840068 } },
    { "experimental.ups.powersummary.presentstatus.voltagenotregulated", VCONV_NONE, 0, 0, 4, { 0x00840004, 0x00840024, 0x00840002, 0x008500db } },
    { "experimental.ups.powersummary.rechargeable", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00840024, 0x0085008b } },
    { "experimental.battery.batteryid", VCONV_NONE, 0, 0, 4, { 0x00840004, 0x00840010, 0x00840012, 0x00840013 } },
    { "experimental.battery.systemid", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00840010, 0x00840011 } },
    { "experimental.battery.chargerid", VCONV_NONE, 0, 0, 4, { 0x00840004, 0x00840010, 0x00840014, 0x00840015 } },
    { "experimental.battery.input_flowid", VCONV_NONE, 0, 0, 4, { 0x00840004, 0x00840010, 0x0084001a, 0x0084001f } },
    { "experimental.battery.input_id", VCONV_NONE, 0, 0, 4, { 0x00840004, 0x00840010, 0x0084001a, 0x0084001b } },
    { "experimental.battery.output_flowid", VCONV_NONE, 0, 0, 4, { 0x00840004, 0x00840010, 0x0084001c, 0x0084001f } },
    { "experimental.battery.output_id", VCONV_NONE, 0, 0, 4, { 0x00840004, 0x00840010, 0x0084001c, 0x0084001d } },
    { "ups.temperature", VCONV_KELVIN, 0, 0, 3, { 0x00840004, 0x00000000, 0xff000040 } },
    { "battery.temperature", VCONV_KELVIN, 0, 0, 3, { 0x00840004, 0x00000000, 0xff000041 } },
    { "output.powerfactor", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00000000, 0xff000042 } },
    { "experimental.control.ups_on", VCONV_NONE, 0, 0, 4, { 0x00840004, 0x00000000, 0xff000043, 0xff000044 } },
    { "experimental.control.clear_fault", VCONV_NONE, 0, 0, 4, { 0x00840004, 0x00000000, 0xff000043, 0xff000045 } },
    { "experimental.control.clear_battery_fault", VCONV_NONE, 0, 0, 4, { 0x00840004, 0x00000000, 0xff000043, 0xff000046 } },
    { "experimental.control.epo_blocked", VCONV_NONE, 0, 0, 4, { 0x00840004, 0x00000000, 0xff000050, 0xff000051 } },
    { "experimental.control.green_mode", VCONV_NONE, 0, 0, 4, { 0x00840004, 0x00000000, 0xff000050, 0xff000052 } },
    { "experimental.control.button_sound", VCONV_NONE, 0, 0, 4, { 0x00840004, 0x00000000, 0xff000050, 0xff000053 } },
    { "experimental.control.audible_alarm", VCONV_NONE, 0, 0, 4, { 0x00840004, 0x00000000, 0xff000050, 0xff000054 } },
    { "output.voltage", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00000000, 0xff000060 } },
    { "experimental.config.overload_clearance_threshold", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00000000, 0xff000066 } },
    { "experimental.config.stb_charge", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00000000, 0xff000067 } },
    { "battery.packs.external", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00000000, 0xff000068 } },
    { "experimental.statistics.mains_loss_counter", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00000000, 0xff000069 } },
    { "experimental.statistics.lowering_AVR_trigger_counter", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00000000, 0xff00006a } },
    { "experimental.statistics.rising_AVR_trigger_counter", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00000000, 0xff00006b } },
    { "experimental.statistics.overload_counter", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00000000, 0xff00006c } },
    { "experimental.statistics.short_circuit_counter", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00000000, 0xff00006d } },
    { "experimental.statistics.discharge_counter", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00000000, 0xff00006e } },
    { "experimental.statistics.overheat_counter", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00000000, 0xff00006f } },
    { "experimental.statistics.mains_operation_time", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00000000, 0xff000070 } },
    { "experimental.statistics.autonomous_operation_time", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00000000, 0xff000071 } },
    { "experimental.statistics.overload_operation_time", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00000000, 0xff000072 } },
    { "experimental.networkcard.config_dhcp_enabled", VCONV_NONE, 0, 0, 4, { 0x00840004, 0x00000000, 0xff000080, 0xff000081 } },
    { "experimental.networkcard.config_ethernet_enabled", VCONV_NONE, 0, 0, 4, { 0x00840004, 0x00000000, 0xff000080, 0xff000082 } },
    { "experimental.networkcard.config_http_enabled", VCONV_NONE, 0, 0, 4, { 0x00840004, 0x00000000, 0xff000080, 0xff000083 } },
    { "experimental.networkcard.config_snmp_enabled", VCONV_NONE, 0, 0, 4, { 0x00840004, 0x00000000, 0xff000080, 0xff000084 } },
    { "experimental.networkcard.config_snmp_trap_enabled", VCONV_NONE, 0, 0, 4, { 0x00840004, 0x00000000, 0xff000080, 0xff000085 } },
    { "experimental.networkcard.config_readonly", VCONV_NONE, 0, 0, 4, { 0x00840004, 0x00000000, 0xff000080, 0xff000086 } },
    { "experimental.networkcard.config_restart_eth", VCONV_NONE, 0, 0, 4, { 0x00840004, 0x00000000, 0xff000080, 0xff00008b } },
    { "ups.realpower.nominal", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x0084001e, 0x00840044 } },
    { "ups.power.nominal", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x0084001e, 0x00840043 } },
    { "output.frequency.nominal", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x0084001e, 0x00840042 } },
    { "experimental.ups.flow_id", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x0084001e, 0x0084001f } },
    { "outlet.1.id", VCONV_NONE, 0, 0, 4, { 0x00840004, 0x00840018, 0x00840020, 0x00840021 } },
    { "experimental.outlet.1.present", VCONV_YESNO, 0, 0, 5, { 0x00840004, 0x00840018, 0x00840020, 0x00840002, 0x00840060 } },
    { "outlet.1.switchable", VCONV_YESNO, 0, 0, 5, { 0x00840004, 0x00840018, 0x00840020, 0x00840002, 0x0084006c } },
    { "outlet.1.status", VCONV_NONE, 0, 0, 5, { 0x00840004, 0x00840018, 0x00840020, 0x00840002, 0x0084006b } },
    { "experimental.outlet.1.undefined", VCONV_NONE, 0, 0, 5, { 0x00840004, 0x00840018, 0x00840020, 0x00840002, 0x00840000 } },
    { "experimental.outlet.1.system_id", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00840018, 0x00840019 } },
    { "experimental.outlet.1.switch_off_control", VCONV_NONE, 0, 0, 4, { 0x00840004, 0x00840018, 0x00840020, 0x00840051 } },
    { "experimental.outlet.1.switch_on_control", VCONV_NONE, 0, 0, 4, { 0x00840004, 0x00840018, 0x00840020, 0x00840050 } },
    { "experimental.powerconverter.input_flow_id", VCONV_NONE, 0, 0, 4, { 0x00840004, 0x00840016, 0x0084001a, 0x0084001f } },
    { "input.frequency", VCONV_NONE, 0, 0, 4, { 0x00840004, 0x00840016, 0x0084001a, 0x00840032 } },
    { "experimental.powerconverter.input_id", VCONV_NONE, 0, 0, 4, { 0x00840004, 0x00840016, 0x0084001a, 0x0084001b } },
    { "input.voltage", VCONV_NONE, 0, 0, 4, { 0x00840004, 0x00840016, 0x0084001a, 0x00840030 } },
    { "output.current", VCONV_NONE, 0, 0, 4, { 0x00840004, 0x00840016, 0x0084001c, 0x00840031 } },
    { "experimental.powerconverter.output_flowid", VCONV_NONE, 0, 0, 4, { 0x00840004, 0x00840016, 0x0084001c, 0x0084001f } },
    { "output.frequency", VCONV_NONE, 0, 0, 4, { 0x00840004, 0x00840016, 0x0084001c, 0x00840032 } },
    { "experimental.powerconverter.output_id", VCONV_NONE, 0, 0, 4, { 0x00840004, 0x00840016, 0x0084001c, 0x0084001d } },
    { "ups.load", VCONV_NONE, 0, 0, 4, { 0x00840004, 0x00840016, 0x0084001c, 0x00840035 } },
    { "output.voltage", VCONV_NONE, 0, 0, 4, { 0x00840004, 0x00840016, 0x0084001c, 0x00840030 } },
    { "experimental.powersummary.capacity_granularity_1", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00840024, 0x0085008d } },
    { "experimental.powersummary.capacity_granularity_2", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00840024, 0x0085008e } },
    { "experimental.powersummary.capacity_mode", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00840024, 0x0085002c } },
    { "battery.capacity", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00840024, 0x00850083 } },
    { "experimental.powersummary.flow_id", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00840024, 0x0084001f } },
    { "battery.capacity", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00840024, 0x00850067 } },
    { "battery.type", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00840024, 0x00850089 } },
    { "experimental.powersummary.rechargeable", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00840024, 0x0085008b } },
    { "battery.voltage", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00840024, 0x00840030 } },
    { "device.mfr", VCONV_STRINGID, 0, 2, 3, { 0x00840004, 0x00840024, 0x008400fd } },
    { "device.model", VCONV_STRINGID, 0, 2, 3, { 0x00840004, 0x00840024, 0x008400fe } },
    { "device.serial", VCONV_STRINGID, 0, 2, 3, { 0x00840004, 0x00840024, 0x008400ff } },
    { "battery.capacity.design", VCONV_NONE, 0, 2, 3, { 0x00840004, 0x00840024, 0x00850083 } },
    { "battery.charge.low", VCONV_NONE, 0, 2, 3, { 0x00840004, 0x00840024, 0x0085008c } },
    { "battery.capacity.full", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00840024, 0x00850067 } },
    { "input.transfer.high", VCONV_NONE, 0, 2, 4, { 0x00840004, 0x00840016, 0x0084001c, 0x00840054 } },
    { "input.transfer.low", VCONV_NONE, 0, 2, 4, { 0x00840004, 0x00840016, 0x0084001c, 0x00840053 } },
    { "output.voltage.nominal", VCONV_NONE, 0, 2, 4, { 0x00840004, 0x0084001e, 0x00ff0004, 0x00840040 } },
    { "battery.voltage.nominal", VCONV_NONE, 1, 2, 3, { 0x00840004, 0x00840024, 0x00840040 } },
    { "input.voltage", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x0084001a, 0x00840030 } },
    { "input.transfer.high", VCONV_NONE, 0, 2, 3, { 0x00840004, 0x0084001a, 0x00840054 } },
    { "input.transfer.low", VCONV_NONE, 0, 2, 3, { 0x00840004, 0x0084001a, 0x00840053 } },
    { "input.voltage.nominal", VCONV_NONE, 0, 2, 3, { 0x00840004, 0x0084001a, 0x00840040 } },
    { "input.voltage.nominal", VCONV_NONE, 0, 2, 3, { 0x00840004, 0x0084001e, 0x00840040 } },
    { "battery.voltage.nominal", VCONV_DIV10, 0, 2, 3, { 0x00840004, 0x00840024, 0x00840040 } },
    { "battery.voltage.nominal", VCONV_NONE, 0, 2, 4, { 0x00840004, 0x00840010, 0x00840012, 0x00840040 } },
    { "battery.voltage", VCONV_DIV10, 0, 0, 3, { 0x00840004, 0x00840024, 0x00840030 } },
    { "battery.charge.warning", VCONV_NONE, 0, 2, 3, { 0x00840004, 0x00840024, 0x0085008c } },
    { "output.voltage", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x0084001c, 0x00840030 } },
    { "output.frequency", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x0084001c, 0x00840032 } },
    { "ups.realpower.nominal", VCONV_NONE, 0, 2, 3, { 0x00840004, 0x0084001c, 0x00840044 } },
    { "ups.realpower.nominal", VCONV_NONE, 0, 2, 3, { 0x00840004, 0x0084001e, 0x00840043 } },
    { "experimental.battery.capacity", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00840024, 0x00850067 } },
    { "experimental.battery.capacity.nominal", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00840024, 0x00850083 } },
    { "ups.power.nominal", VCONV_NONE, 0, 1, 4, { 0x00840004, 0x0084001e, 0x00ff0004, 0x00840043 } },
    { "output.voltage.nominal", VCONV_NONE, 0, 1, 4, { 0x00840004, 0x0084001e, 0x00ff0004, 0x00840040 } },
    { "output.frequency", VCONV_NONE, 2, 0, 4, { 0x00840004, 0x00840016, 0x0084001c, 0x00840032 } },
    { "output.frequency.nominal", VCONV_NONE, 0, 1, 4, { 0x00840004, 0x0084001e, 0x00ff0004, 0x00840042 } },
    { "output.transfer.high", VCONV_NONE, 1, 1, 4, { 0x00840004, 0x00840016, 0x0084001c, 0x00840054 } },
    { "output.transfer.low", VCONV_NONE, 1, 1, 4, { 0x00840004, 0x00840016, 0x0084001c, 0x00840053 } },
    { "input.frequency", VCONV_NONE, 2, 0, 5, { 0x00840004, 0x00840016, 0x0084001a, 0x00ff0001, 0x00840032 } },
    { "input.transfer.low", VCONV_NONE, 0, 1, 4, { 0x00840004, 0x00840016, 0x0084001c, 0xffff0057 } },
    { "input.transfer.high", VCONV_NONE, 0, 1, 4, { 0x00840004, 0x00840016, 0x0084001c, 0xffff0058 } },
    { "input.frequency.transfer.low", VCONV_NONE, 0, 1, 4, { 0x00840004, 0x00840016, 0x0084001c, 0xffff00f9 } },
    { "input.frequency.transfer.high", VCONV_NONE, 0, 1, 4, { 0x00840004, 0x00840016, 0x0084001c, 0xffff00f8 } },
    { "battery.mfr.date", VCONV_STRINGID, 0, 2, 3, { 0x00840004, 0x00840024, 0x0085008f } },
    { "battery.current", VCONV_NONE, 3, 0, 3, { 0x00840004, 0x00840024, 0x00840031 } },
    { "battery.capacity", VCONV_NONE, 0, 2, 3, { 0x00840004, 0x00840024, 0x00850083 } },
    { "battery.charge", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00840012, 0x00850066 } },
    { "battery.mfr.date", VCONV_DATE, 0, 2, 3, { 0x00840004, 0x00840012, 0x00850085 } },
    { "ups.date", VCONV_DATE, 0, 2, 3, { 0x00840004, 0x00840024, 0x00850085 } },
    { "input.frequency", VCONV_NONE, 1, 0, 3, { 0x00840004, 0x0084001a, 0x00840032 } },
    { "output.voltage.nominal", VCONV_NONE, 0, 2, 3, { 0x00840004, 0x0084001c, 0x00840040 } },
    { "ups.serial", VCONV_STRINGID, 0, 0, 2, { 0x00020004, 0x00020086 } },
    { "ups.mfr", VCONV_STRINGID, 0, 0, 2, { 0x00020004, 0x00020087 } },
    { "ups.mfr.date", VCONV_DATE, 0, 0, 2, { 0x00020004, 0x00020085 } },
    { "battery.temperature", VCONV_NONE, 0, 0, 3, { 0x00020004, 0x00020010, 0x00020036 } },
    { "battery.temperature", VCONV_NONE, 1, 0, 3, { 0x00840004, 0x00840012, 0x00840036 } },
    { "battery.charge", VCONV_NONE, 0, 0, 3, { 0x00020004, 0x00020010, 0x00020030 } },
    { "input.frequency", VCONV_NONE, 0, 0, 4, { 0x00020004, 0x00020016, 0x0002001a, 0x00020032 } },
    { "ups.load", VCONV_NONE, 0, 0, 4, { 0x00020004, 0x00020016, 0x0002001c, 0x00020035 } },
    { "output.frequency", VCONV_NONE, 0, 0, 4, { 0x00020004, 0x00020016, 0x0002001c, 0x00020032 } },
    { "ups.test.result", VCONV_TEST, 0, 0, 3, { 0x00020004, 0x00020016, 0x00020058 } },
    { "ups.delay.shutdown", VCONV_NONE, 0, 0, 3, { 0x00020004, 0x00020016, 0x00020057 } },
    { "ups.delay.start", VCONV_NONE, 0, 0, 3, { 0x00020004, 0x00020016, 0x00020056 } },
    { "BOOL", VCONV_YESNO, 0, 0, 4, { 0x00840004, 0x00840024, 0x00840002, 0x00840062 } },
    { "BOOL", VCONV_YESNO, 0, 0, 4, { 0x00840004, 0x00840024, 0x00840002, 0x00840061 } },
    { "ups.realpower.nominal", VCONV_NONE, 0, 0, 4, { 0x00840004, 0x0084001e, 0x00ff0004, 0x00840044 } },
    { "output.voltage.nominal", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00840024, 0x00840040 } },
    { "device.part", VCONV_STRINGID, 0, 2, 4, { 0x00840004, 0xffff0010, 0x00ff0001, 0xffff007f } },
    { "ups.timer.start", VCONV_NONE, 0, 0, 4, { 0x00840004, 0x00840018, 0x00840020, 0xffff0056 } },
    { "ups.power", VCONV_NONE, 1, 0, 4, { 0x00840004, 0x00840018, 0x00840020, 0x00840033 } },
    { "ups.power", VCONV_NONE, 1, 0, 4, { 0x00840004, 0x00840016, 0x0084001c, 0x00840033 } },
    { "ups.realpower.nominal", VCONV_NONE, 0, 2, 3, { 0x00840004, 0x0084001e, 0x00840044 } },
    { "ups.firmware", VCONV_NONE, 0, 2, 4, { 0x00840004, 0xffff0010, 0x00ff0001, 0xffff007c } },
    { "ups.watchdog.status", VCONV_NONE, 0, 0, 4, { 0x00840004, 0x00840018, 0x00840020, 0xffff0092 } },
    { "ups.load.nominal", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x0084001e, 0x00840045 } },
    { "input.voltage.nominal", VCONV_NONE, 0, 2, 4, { 0x00840004, 0x00840024, 0x0084001a, 0x00840040 } },
    { "input.transfer.low", VCONV_NONE, 1, 1, 4, { 0x00840004, 0x00840016, 0x0084001c, 0x00840053 } },
    { "input.transfer.low.max", VCONV_NONE, 0, 2, 4, { 0x00840004, 0x00840016, 0x0084001c, 0xffff0057 } },
    { "input.transfer.low.min", VCONV_NONE, 0, 2, 4, { 0x00840004, 0x00840016, 0x0084001c, 0xffff0058 } },
    { "input.transfer.high", VCONV_NONE, 1, 1, 4, { 0x00840004, 0x00840016, 0x0084001c, 0x00840054 } },
    { "input.transfer.high.max", VCONV_NONE, 0, 2, 4, { 0x00840004, 0x00840016, 0x0084001c, 0xffff0059 } },
    { "input.transfer.high.min", VCONV_NONE, 0, 2, 4, { 0x00840004, 0x00840016, 0x0084001c, 0xffff005a } },
    { "output.voltage.nominal", VCONV_NONE, 0, 2, 3, { 0x00840004, 0x0084001e, 0x00840040 } },
    { "output.frequency.nominal", VCONV_NONE, 0, 2, 3, { 0x00840004, 0x0084001e, 0x00840042 } },
};
const size_t ups_vartab_row_count = 405;

static const uint16_t s_explore[] = { 0 };
static const uint16_t s_mge[] = { 0, 1, 2, 3, 4, 5, 6, 7, 6, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140 };
static const uint16_t s_apc[] = { 1, 141, 142, 143, 5, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 22, 23, 24, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178 };
static const uint16_t s_arduino[] = { 22, 23, 24, 9, 179, 180, 5, 145, 1, 141, 181, 20, 44, 89 };
static const uint16_t s_belkin[] = { 182, 183, 142, 5, 151, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 164, 204, 205, 1, 206, 207, 208, 209, 210, 211, 212, 213, 214 };
static const uint16_t s_cps[] = { 151, 152, 215, 142, 141, 5, 145, 216, 207, 162, 217, 218, 219, 220, 166, 155, 156, 157, 221, 30, 168, 167, 171, 172, 169, 170, 173, 222 };
static const uint16_t s_delta_ups[] = { 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 1, 235, 141, 181, 236, 5, 9, 237, 238, 239, 240, 89, 101, 241, 162, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251 };
static const uint16_t s_ecoflow[] = { 162, 252, 253, 251, 250, 254, 238, 9, 255, 164, 256, 257, 258, 1, 141, 145, 147, 181 };
static const uint16_t s_ever[] = { 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299, 210, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312, 36, 31, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325, 20, 326, 1, 6, 5, 327, 23 };
static const uint16_t s_idowell[] = { 328, 329, 330, 331, 1, 3, 332, 333, 5, 9, 22, 23, 20, 35, 334, 335, 89, 147, 336, 337, 102 };
static const uint16_t s_legrand[] = { 338, 339, 340, 335, 341, 342, 343, 344, 345, 1, 346, 3, 347, 348, 207, 212, 349, 350, 28 };
static const uint16_t s_liebert[] = { 180, 1, 351, 352, 5, 151, 20, 353, 25, 28, 89, 354, 355, 356, 357, 358, 44, 359, 360, 361, 362, 363 };
static const uint16_t s_openups[] = { 205, 9, 364, 180, 365, 366, 1, 183, 142, 5 };
static const uint16_t s_powercom[] = { 1, 367, 183, 142, 5, 368, 9, 207, 369, 161, 167, 341, 370, 173, 371, 176, 372, 373, 374, 375, 376, 377, 378, 379, 380, 381, 382, 383 };
static const uint16_t s_powervar[] = { 151, 1, 324, 384, 385 };
static const uint16_t s_salicru[] = { 151, 1, 142, 141, 5, 145, 216, 180, 207, 162, 217, 166, 370, 168, 167, 334, 335, 176, 173, 222, 20, 25, 386, 36, 57, 44, 101, 89, 387, 25 };
static const uint16_t s_tripplite[] = { 388, 1, 235, 141, 142, 5, 233, 236, 249, 389, 250, 251, 242, 162, 244, 390, 391, 392, 245, 246, 212, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402, 403, 404 };
static const uint16_t s_common[] = { 1, 3, 5, 6, 9, 20, 22, 23, 24, 25, 28, 30, 31, 35, 36, 44, 57, 89, 101, 102, 141, 142, 145, 147, 151, 152, 155, 156, 157, 161, 162, 164, 166, 167, 168, 169, 170, 171, 172, 173, 176, 180, 181, 183, 205, 207, 210, 212, 216, 217, 222, 233, 235, 236, 238, 242, 244, 245, 246, 249, 250, 251, 324, 334, 335, 341, 370 };

static const uint16_t *const s_lists[] = {
    s_explore,
    s_mge,
    s_apc,
    s_arduino,
    s_belkin,
    s_cps,
    s_delta_ups,
    s_ecoflow,
    s_ever,
    s_idowell,
    s_legrand,
    s_liebert,
    s_openups,
    s_powercom,
    s_powervar,
    s_salicru,
    s_tripplite,
};
static const uint16_t s_list_len[] = {
    0,
    142,
    43,
    14,
    38,
    28,
    37,
    18,
    77,
    21,
    19,
    22,
    10,
    28,
    5,
    30,
    33,
};

const ups_vartab_sub_t ups_vartab_subs[] = {
    { "explore", 0 },
    { "mge", 1 },
    { "apc", 2 },
    { "arduino", 3 },
    { "belkin", 4 },
    { "cps", 5 },
    { "delta_ups", 6 },
    { "ecoflow", 7 },
    { "ever", 8 },
    { "idowell", 9 },
    { "legrand", 10 },
    { "liebert", 11 },
    { "openups", 12 },
    { "powercom", 13 },
    { "powervar", 14 },
    { "salicru", 15 },
    { "tripplite", 16 },
};
const size_t ups_vartab_sub_count = 17;

/* USB IDs each subdriver claims, in NUT's subdriver order: first match wins. */
const ups_vartab_id_t ups_vartab_ids[] = {
    { 0x0463, 0x0001, 1 },  /* mge */
    { 0x0463, 0xffff, 1 },  /* mge */
    { 0x047c, 0xffff, 1 },  /* mge */
    { 0x0592, 0x0004, 1 },  /* mge */
    { 0x03f0, 0x1fe5, 1 },  /* mge */
    { 0x03f0, 0x1fe6, 1 },  /* mge */
    { 0x03f0, 0x1fe7, 1 },  /* mge */
    { 0x03f0, 0x1fe8, 1 },  /* mge */
    { 0x2b2d, 0xffff, 1 },  /* mge */
    { 0x06da, 0xffff, 1 },  /* mge */
    { 0x04b3, 0x0001, 1 },  /* mge */
    { 0x09d6, 0x0001, 1 },  /* mge */
    { 0x051d, 0x0000, 2 },  /* apc */
    { 0x051d, 0x0002, 2 },  /* apc */
    { 0x051d, 0x0003, 2 },  /* apc */
    { 0x051d, 0x0004, 2 },  /* apc */
    { 0x051d, 0x0005, 2 },  /* apc */
    { 0x2341, 0x0036, 3 },  /* arduino */
    { 0x2341, 0x8036, 3 },  /* arduino */
    { 0x050d, 0x0980, 4 },  /* belkin */
    { 0x050d, 0x0900, 4 },  /* belkin */
    { 0x050d, 0x0910, 4 },  /* belkin */
    { 0x050d, 0x0912, 4 },  /* belkin */
    { 0x050d, 0x0551, 4 },  /* belkin */
    { 0x050d, 0x0750, 4 },  /* belkin */
    { 0x050d, 0x0751, 4 },  /* belkin */
    { 0x050d, 0x0375, 4 },  /* belkin */
    { 0x050d, 0x0f51, 4 },  /* belkin */
    { 0x050d, 0x1100, 4 },  /* belkin */
    { 0x10af, 0x0000, 4 },  /* belkin */
    { 0x10af, 0x0001, 4 },  /* belkin */
    { 0x10af, 0x0002, 4 },  /* belkin */
    { 0x10af, 0x0004, 4 },  /* belkin */
    { 0x10af, 0x0008, 4 },  /* belkin */
    { 0x0764, 0x0005, 5 },  /* cps */
    { 0x0764, 0x0501, 5 },  /* cps */
    { 0x0764, 0x0601, 5 },  /* cps */
    { 0x0483, 0xa430, 5 },  /* cps */
    { 0x05dd, 0x041b, 6 },  /* delta_ups */
    { 0x3746, 0xffff, 7 },  /* ecoflow */
    { 0x0483, 0xa113, 8 },  /* ever */
    { 0x2e51, 0xffff, 8 },  /* ever */
    { 0x2e51, 0x0000, 8 },  /* ever */
    { 0x075d, 0x0300, 9 },  /* idowell */
    { 0x06da, 0xffff, 9 },  /* idowell */
    { 0x06da, 0xffff, 11 },  /* liebert */
    { 0x04d8, 0xd004, 12 },  /* openups */
    { 0x04d8, 0xd005, 12 },  /* openups */
    { 0x0d9f, 0x00a2, 13 },  /* powercom */
    { 0x0d9f, 0x00a3, 13 },  /* powercom */
    { 0x0d9f, 0x00a4, 13 },  /* powercom */
    { 0x0d9f, 0x00a5, 13 },  /* powercom */
    { 0x0d9f, 0x00a6, 13 },  /* powercom */
    { 0x0d9f, 0x0004, 13 },  /* powercom */
    { 0x0d9f, 0x0001, 13 },  /* powercom */
    { 0x4234, 0x0002, 14 },  /* powervar */
    { 0x2e66, 0x0101, 15 },  /* salicru */
    { 0x2e66, 0x0201, 15 },  /* salicru */
    { 0x2e66, 0x0202, 15 },  /* salicru */
    { 0x2e66, 0x0203, 15 },  /* salicru */
    { 0x2e66, 0x0300, 15 },  /* salicru */
    { 0x2e66, 0x0302, 15 },  /* salicru */
    { 0x09ae, 0x1003, 16 },  /* tripplite */
    { 0x09ae, 0x1007, 16 },  /* tripplite */
    { 0x09ae, 0x1008, 16 },  /* tripplite */
    { 0x09ae, 0x1009, 16 },  /* tripplite */
    { 0x09ae, 0x1010, 16 },  /* tripplite */
    { 0x09ae, 0x1330, 16 },  /* tripplite */
    { 0x09ae, 0x2005, 16 },  /* tripplite */
    { 0x09ae, 0x2007, 16 },  /* tripplite */
    { 0x09ae, 0x2008, 16 },  /* tripplite */
    { 0x09ae, 0x2009, 16 },  /* tripplite */
    { 0x09ae, 0x2010, 16 },  /* tripplite */
    { 0x09ae, 0x2011, 16 },  /* tripplite */
    { 0x09ae, 0x2012, 16 },  /* tripplite */
    { 0x09ae, 0x2013, 16 },  /* tripplite */
    { 0x09ae, 0x2014, 16 },  /* tripplite */
    { 0x09ae, 0x3008, 16 },  /* tripplite */
    { 0x09ae, 0x3009, 16 },  /* tripplite */
    { 0x09ae, 0x3010, 16 },  /* tripplite */
    { 0x09ae, 0x3011, 16 },  /* tripplite */
    { 0x09ae, 0x3012, 16 },  /* tripplite */
    { 0x09ae, 0x3013, 16 },  /* tripplite */
    { 0x09ae, 0x3014, 16 },  /* tripplite */
    { 0x09ae, 0x3015, 16 },  /* tripplite */
    { 0x09ae, 0x3016, 16 },  /* tripplite */
    { 0x09ae, 0x3024, 16 },  /* tripplite */
    { 0x09ae, 0x4001, 16 },  /* tripplite */
    { 0x09ae, 0x4002, 16 },  /* tripplite */
    { 0x09ae, 0x4003, 16 },  /* tripplite */
    { 0x09ae, 0x4004, 16 },  /* tripplite */
    { 0x09ae, 0x4005, 16 },  /* tripplite */
    { 0x09ae, 0x4006, 16 },  /* tripplite */
    { 0x09ae, 0x4007, 16 },  /* tripplite */
    { 0x09ae, 0x4008, 16 },  /* tripplite */
    { 0x03f0, 0x0001, 16 },  /* tripplite */
    { 0x03f0, 0x1fe0, 16 },  /* tripplite */
    { 0x03f0, 0x1fe1, 16 },  /* tripplite */
    { 0x03f0, 0x1fe2, 16 },  /* tripplite */
    { 0x03f0, 0x1fe3, 16 },  /* tripplite */
    { 0x03f0, 0x1f06, 16 },  /* tripplite */
    { 0x03f0, 0x1f08, 16 },  /* tripplite */
    { 0x03f0, 0x1f09, 16 },  /* tripplite */
    { 0x03f0, 0x1f0a, 16 },  /* tripplite */
    { 0x05dd, 0xa011, 16 },  /* tripplite */
    { 0x05dd, 0xa0a0, 16 },  /* tripplite */
};
const size_t ups_vartab_id_count = sizeof(ups_vartab_ids) / sizeof(ups_vartab_ids[0]);

const uint16_t *ups_vartab_list(int sub, size_t *len)
{
    if (sub < 0 || sub >= (int)(sizeof(s_lists) / sizeof(s_lists[0]))) {
        *len = 67;
        return s_common;
    }
    *len = s_list_len[sub];
    return s_lists[sub];
}

/* Vendor-page usages a row reads, sorted, for hid_parser's keep test. */
const uint32_t ups_vartab_vendor_usages[70] = {
    0xff000040, 0xff000041, 0xff000042, 0xff000044, 0xff000045, 0xff000046,
    0xff000051, 0xff000052, 0xff000053, 0xff000054, 0xff000060, 0xff000066,
    0xff000067, 0xff000068, 0xff000069, 0xff00006a, 0xff00006b, 0xff00006c,
    0xff00006d, 0xff00006e, 0xff00006f, 0xff000070, 0xff000071, 0xff000072,
    0xff000081, 0xff000082, 0xff000083, 0xff000084, 0xff000085, 0xff000086,
    0xff00008b, 0xff0100d0, 0xff86007c, 0xff86007d, 0xff86007e, 0xffff0043,
    0xffff0044, 0xffff0045, 0xffff0046, 0xffff0047, 0xffff0049, 0xffff004b,
    0xffff004d, 0xffff004e, 0xffff0050, 0xffff0051, 0xffff0052, 0xffff0053,
    0xffff0056, 0xffff0057, 0xffff0058, 0xffff0059, 0xffff005a, 0xffff005b,
    0xffff005c, 0xffff005d, 0xffff005e, 0xffff005f, 0xffff0069, 0xffff007c,
    0xffff007f, 0xffff0081, 0xffff0086, 0xffff0092, 0xffff0097, 0xffff009c,
    0xffff00ba, 0xffff00f1, 0xffff00f8, 0xffff00f9,
};
const size_t ups_vartab_vendor_usage_count = 70;
