/* SPDX-License-Identifier: GPL-3.0-or-later
 *
 * GENERATED by tools/gen-vartab.py from NUT 3154ca0 2026-09-23. Do not edit:
 * change the generator, or NUT, and regenerate.
 *
 * NUT (networkupstools.org) is GPL-2.0-or-later; its usbhid-ups tables are
 * the source of every row here. */
#include "ups_vartab.h"

const ups_vartab_row_t ups_vartab_rows[407] = {
    { "device.usb.version", VCONV_STRINGID, 0, 2, 4, { 0x00840004, 0xffff00e5, 0xffff0005, 0xffff00f1 } },
    { "battery.charge", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00840024, 0x00850066 } },
    { "battery.charge.low", VCONV_NONE, 0, 1, 3, { 0x00840004, 0x00840024, 0xffff004d } },
    { "battery.charge.low", VCONV_NONE, 0, 2, 3, { 0x00840004, 0x00840024, 0x00850029 } },
    { "battery.charge.restart", VCONV_NONE, 0, 1, 3, { 0x00840004, 0x00840024, 0xffff005f } },
    { "battery.runtime", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00840024, 0x00850068 } },
    { "battery.runtime.low", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00840024, 0x0085002a } },
    { "battery.runtime.elapsed", VCONV_NONE, 0, 0, 7, { 0x00840004, 0xffff0004, 0x0084001a, 0x00ff0001, 0xffff0003, 0x00ff0001, 0xffff0097 } },
    { "battery.temperature", VCONV_KELVIN, 0, 0, 4, { 0x00840004, 0x00840010, 0x00840012, 0x00840036 } },
    { "battery.type", VCONV_STRINGID, 0, 2, 3, { 0x00840004, 0x00840024, 0x00850089 } },
    { "battery.voltage", VCONV_NONE, 1, 0, 3, { 0x00840004, 0x00840010, 0x00840030 } },
    { "battery.voltage.nominal", VCONV_NONE, 0, 2, 3, { 0x00840004, 0x00840010, 0x00840040 } },
    { "battery.protection", VCONV_YESNO, 0, 1, 4, { 0x00840004, 0x00840010, 0x00840012, 0xffff0049 } },
    { "battery.energysave", VCONV_YESNO, 0, 1, 5, { 0x00840004, 0x00840016, 0x0084001a, 0x00ff0003, 0xffff0046 } },
    { "battery.energysave.load", VCONV_NONE, 0, 1, 5, { 0x00840004, 0x00840016, 0x0084001a, 0x00ff0003, 0x00840045 } },
    { "battery.energysave.delay", VCONV_NONE, 0, 1, 6, { 0x00840004, 0x00840016, 0x0084001a, 0x00ff0003, 0xffff0046, 0xffff005d } },
    { "battery.energysave.delay", VCONV_NONE, 0, 1, 5, { 0x00840004, 0x00840016, 0x0084001a, 0x00ff0003, 0xffff005d } },
    { "battery.energysave.realpower", VCONV_NONE, 0, 1, 5, { 0x00840004, 0x00840016, 0x0084001a, 0x00ff0003, 0x00840044 } },
    { "ups.efficiency", VCONV_NONE, 0, 0, 4, { 0x00840004, 0x00840016, 0x0084001c, 0xffff0086 } },
    { "ups.firmware", VCONV_STRINGID, 0, 2, 3, { 0x00840004, 0x00840024, 0xffff00f1 } },
    { "ups.load", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00840024, 0x00840035 } },
    { "ups.load.high", VCONV_NONE, 0, 1, 4, { 0x00840004, 0x0084001e, 0x00ff0004, 0x00840045 } },
    { "ups.timer.start", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00840024, 0x00840056 } },
    { "ups.timer.shutdown", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00840024, 0x00840057 } },
    { "ups.timer.reboot", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00840024, 0x00840055 } },
    { "ups.test.result", VCONV_TEST, 0, 0, 4, { 0x00840004, 0x00840010, 0x00840012, 0x00840058 } },
    { "ups.test.interval", VCONV_NONE, 0, 1, 4, { 0x00840004, 0x00840010, 0x00840012, 0xffff0045 } },
    { "ups.beeper.status", VCONV_BEEPER, 0, 1, 4, { 0x00840004, 0x00840010, 0x00840012, 0x0084005a } },
    { "ups.beeper.status", VCONV_BEEPER, 0, 1, 3, { 0x00840004, 0x00840024, 0x0084005a } },
    { "ups.beeper.status", VCONV_BEEPER, 0, 1, 2, { 0x00840004, 0x0084005a } },
    { "ups.temperature", VCONV_KELVIN, 0, 0, 3, { 0x00840004, 0x00840024, 0x00840036 } },
    { "ups.power", VCONV_NONE, 0, 0, 4, { 0x00840004, 0x00840016, 0x0084001c, 0x00840033 } },
    { "ups.L1.power", VCONV_NONE, 0, 0, 6, { 0x00840004, 0x00840016, 0x0084001c, 0xffff0010, 0x00ff0001, 0x00840033 } },
    { "ups.L2.power", VCONV_NONE, 0, 0, 6, { 0x00840004, 0x00840016, 0x0084001c, 0xffff0010, 0x00ff0002, 0x00840033 } },
    { "ups.L3.power", VCONV_NONE, 0, 0, 6, { 0x00840004, 0x00840016, 0x0084001c, 0xffff0010, 0x00ff0003, 0x00840033 } },
    { "ups.power.nominal", VCONV_NONE, 0, 2, 4, { 0x00840004, 0x0084001e, 0x00ff0004, 0x00840043 } },
    { "ups.realpower", VCONV_NONE, 0, 0, 4, { 0x00840004, 0x00840016, 0x0084001c, 0x00840034 } },
    { "ups.L1.realpower", VCONV_NONE, 0, 0, 6, { 0x00840004, 0x00840016, 0x0084001c, 0xffff0010, 0x00ff0001, 0x00840034 } },
    { "ups.L2.realpower", VCONV_NONE, 0, 0, 6, { 0x00840004, 0x00840016, 0x0084001c, 0xffff0010, 0x00ff0002, 0x00840034 } },
    { "ups.L3.realpower", VCONV_NONE, 0, 0, 6, { 0x00840004, 0x00840016, 0x0084001c, 0xffff0010, 0x00ff0003, 0x00840034 } },
    { "ups.realpower.nominal", VCONV_NONE, 0, 2, 4, { 0x00840004, 0x0084001e, 0x00ff0004, 0x00840044 } },
    { "ups.start.auto", VCONV_YESNO, 0, 1, 5, { 0x00840004, 0x00840016, 0x0084001a, 0x00ff0001, 0xffff0043 } },
    { "ups.start.battery", VCONV_YESNO, 0, 1, 5, { 0x00840004, 0x00840016, 0x0084001a, 0x00ff0003, 0xffff0047 } },
    { "ups.start.reboot", VCONV_YESNO, 0, 1, 4, { 0x00840004, 0x00840016, 0x0084001c, 0xffff0044 } },
    { "input.voltage", VCONV_NONE, 1, 0, 5, { 0x00840004, 0x00840016, 0x0084001a, 0x00ff0001, 0x00840030 } },
    { "input.L1-N.voltage", VCONV_NONE, 1, 0, 7, { 0x00840004, 0x00840016, 0x0084001a, 0x00ff0001, 0xffff0010, 0x00ff0001, 0x00840030 } },
    { "input.L2-N.voltage", VCONV_NONE, 1, 0, 7, { 0x00840004, 0x00840016, 0x0084001a, 0x00ff0001, 0xffff0010, 0x00ff0002, 0x00840030 } },
    { "input.L3-N.voltage", VCONV_NONE, 1, 0, 7, { 0x00840004, 0x00840016, 0x0084001a, 0x00ff0001, 0xffff0010, 0x00ff0003, 0x00840030 } },
    { "input.L1-L2.voltage", VCONV_NONE, 1, 0, 7, { 0x00840004, 0x00840016, 0x0084001a, 0x00ff0001, 0xffff0010, 0x00ff000c, 0x00840030 } },
    { "input.L2-L3.voltage", VCONV_NONE, 1, 0, 7, { 0x00840004, 0x00840016, 0x0084001a, 0x00ff0001, 0xffff0010, 0x00ff0017, 0x00840030 } },
    { "input.L3-L1.voltage", VCONV_NONE, 1, 0, 7, { 0x00840004, 0x00840016, 0x0084001a, 0x00ff0001, 0xffff0010, 0x00ff001f, 0x00840030 } },
    { "input.voltage.nominal", VCONV_NONE, 0, 2, 4, { 0x00840004, 0x0084001e, 0x00ff0001, 0x00840040 } },
    { "input.current", VCONV_NONE, 2, 0, 5, { 0x00840004, 0x00840016, 0x0084001a, 0x00ff0001, 0x00840031 } },
    { "input.L1.current", VCONV_NONE, 1, 0, 7, { 0x00840004, 0x00840016, 0x0084001a, 0x00ff0001, 0xffff0010, 0x00ff0001, 0x00840031 } },
    { "input.L2.current", VCONV_NONE, 1, 0, 7, { 0x00840004, 0x00840016, 0x0084001a, 0x00ff0001, 0xffff0010, 0x00ff0002, 0x00840031 } },
    { "input.L3.current", VCONV_NONE, 1, 0, 7, { 0x00840004, 0x00840016, 0x0084001a, 0x00ff0001, 0xffff0010, 0x00ff0003, 0x00840031 } },
    { "input.current.nominal", VCONV_NONE, 2, 2, 4, { 0x00840004, 0x0084001e, 0x00ff0001, 0x00840041 } },
    { "input.frequency", VCONV_NONE, 1, 0, 5, { 0x00840004, 0x00840016, 0x0084001a, 0x00ff0001, 0x00840032 } },
    { "input.frequency.nominal", VCONV_NONE, 0, 2, 4, { 0x00840004, 0x0084001e, 0x00ff0001, 0x00840042 } },
    { "input.transfer.low", VCONV_NONE, 0, 1, 4, { 0x00840004, 0x00840016, 0x0084001c, 0x00840053 } },
    { "input.transfer.eco.low", VCONV_NONE, 0, 1, 4, { 0x00840004, 0x00840016, 0x0084001c, 0xffff005a } },
    { "input.transfer.bypass.low", VCONV_NONE, 0, 1, 4, { 0x00840004, 0x00840016, 0x0084001c, 0xffff0057 } },
    { "input.transfer.boost.low", VCONV_NONE, 0, 1, 4, { 0x00840004, 0x00840016, 0x0084001c, 0xffff0050 } },
    { "input.transfer.boost.high", VCONV_NONE, 0, 1, 4, { 0x00840004, 0x00840016, 0x0084001c, 0xffff0051 } },
    { "input.transfer.trim.low", VCONV_NONE, 0, 1, 4, { 0x00840004, 0x00840016, 0x0084001c, 0xffff0052 } },
    { "input.transfer.high", VCONV_NONE, 0, 1, 4, { 0x00840004, 0x00840016, 0x0084001c, 0x00840054 } },
    { "input.transfer.eco.high", VCONV_NONE, 0, 1, 4, { 0x00840004, 0x00840016, 0x0084001c, 0xffff005b } },
    { "input.transfer.bypass.high", VCONV_NONE, 0, 1, 4, { 0x00840004, 0x00840016, 0x0084001c, 0xffff0058 } },
    { "input.transfer.frequency.bypass.range", VCONV_NONE, 0, 1, 4, { 0x00840004, 0x00840016, 0x0084001c, 0xffff0059 } },
    { "input.transfer.frequency.eco.range", VCONV_NONE, 0, 1, 4, { 0x00840004, 0x00840016, 0x0084001c, 0xffff005c } },
    { "input.transfer.hysteresis", VCONV_NONE, 0, 1, 4, { 0x00840004, 0x00840016, 0x0084001c, 0xffff009c } },
    { "input.transfer.trim.high", VCONV_NONE, 0, 1, 4, { 0x00840004, 0x00840016, 0x0084001c, 0xffff0053 } },
    { "input.voltage.extended", VCONV_YESNO, 0, 1, 4, { 0x00840004, 0x00840016, 0x0084001c, 0xffff004b } },
    { "input.frequency.extended", VCONV_YESNO, 0, 1, 4, { 0x00840004, 0x00840016, 0x0084001c, 0xffff004e } },
    { "input.bypass.voltage", VCONV_NONE, 1, 0, 5, { 0x00840004, 0x00840016, 0x0084001a, 0x00ff0002, 0x00840030 } },
    { "input.bypass.L1-N.voltage", VCONV_NONE, 1, 0, 7, { 0x00840004, 0x00840016, 0x0084001a, 0x00ff0002, 0xffff0010, 0x00ff0001, 0x00840030 } },
    { "input.bypass.L2-N.voltage", VCONV_NONE, 1, 0, 7, { 0x00840004, 0x00840016, 0x0084001a, 0x00ff0002, 0xffff0010, 0x00ff0002, 0x00840030 } },
    { "input.bypass.L3-N.voltage", VCONV_NONE, 1, 0, 7, { 0x00840004, 0x00840016, 0x0084001a, 0x00ff0002, 0xffff0010, 0x00ff0003, 0x00840030 } },
    { "input.bypass.L1-L2.voltage", VCONV_NONE, 1, 0, 7, { 0x00840004, 0x00840016, 0x0084001a, 0x00ff0002, 0xffff0010, 0x00ff000c, 0x00840030 } },
    { "input.bypass.L2-L3.voltage", VCONV_NONE, 1, 0, 7, { 0x00840004, 0x00840016, 0x0084001a, 0x00ff0002, 0xffff0010, 0x00ff0017, 0x00840030 } },
    { "input.bypass.L3-L1.voltage", VCONV_NONE, 1, 0, 7, { 0x00840004, 0x00840016, 0x0084001a, 0x00ff0002, 0xffff0010, 0x00ff001f, 0x00840030 } },
    { "input.bypass.voltage.nominal", VCONV_NONE, 0, 2, 4, { 0x00840004, 0x0084001e, 0x00ff0002, 0x00840040 } },
    { "input.bypass.current", VCONV_NONE, 2, 0, 5, { 0x00840004, 0x00840016, 0x0084001a, 0x00ff0002, 0x00840031 } },
    { "input.bypass.L1.current", VCONV_NONE, 1, 0, 7, { 0x00840004, 0x00840016, 0x0084001a, 0x00ff0002, 0xffff0010, 0x00ff0001, 0x00840031 } },
    { "input.bypass.L2.current", VCONV_NONE, 1, 0, 7, { 0x00840004, 0x00840016, 0x0084001a, 0x00ff0002, 0xffff0010, 0x00ff0002, 0x00840031 } },
    { "input.bypass.L3.current", VCONV_NONE, 1, 0, 7, { 0x00840004, 0x00840016, 0x0084001a, 0x00ff0002, 0xffff0010, 0x00ff0003, 0x00840031 } },
    { "input.bypass.current.nominal", VCONV_NONE, 2, 2, 4, { 0x00840004, 0x0084001e, 0x00ff0002, 0x00840041 } },
    { "input.bypass.frequency", VCONV_NONE, 1, 0, 5, { 0x00840004, 0x00840016, 0x0084001a, 0x00ff0002, 0x00840032 } },
    { "input.bypass.frequency.nominal", VCONV_NONE, 0, 2, 4, { 0x00840004, 0x0084001e, 0x00ff0002, 0x00840042 } },
    { "output.voltage", VCONV_NONE, 1, 0, 4, { 0x00840004, 0x00840016, 0x0084001c, 0x00840030 } },
    { "output.L1-N.voltage", VCONV_NONE, 1, 0, 6, { 0x00840004, 0x00840016, 0x0084001c, 0xffff0010, 0x00ff0001, 0x00840030 } },
    { "output.L2-N.voltage", VCONV_NONE, 1, 0, 6, { 0x00840004, 0x00840016, 0x0084001c, 0xffff0010, 0x00ff0002, 0x00840030 } },
    { "output.L3-N.voltage", VCONV_NONE, 1, 0, 6, { 0x00840004, 0x00840016, 0x0084001c, 0xffff0010, 0x00ff0003, 0x00840030 } },
    { "output.L1-L2.voltage", VCONV_NONE, 1, 0, 6, { 0x00840004, 0x00840016, 0x0084001c, 0xffff0010, 0x00ff000c, 0x00840030 } },
    { "output.L2-L3.voltage", VCONV_NONE, 1, 0, 6, { 0x00840004, 0x00840016, 0x0084001c, 0xffff0010, 0x00ff0017, 0x00840030 } },
    { "output.L3-L1.voltage", VCONV_NONE, 1, 0, 6, { 0x00840004, 0x00840016, 0x0084001c, 0xffff0010, 0x00ff001f, 0x00840030 } },
    { "output.current", VCONV_NONE, 2, 0, 4, { 0x00840004, 0x00840016, 0x0084001c, 0x00840031 } },
    { "output.L1.current", VCONV_NONE, 1, 0, 6, { 0x00840004, 0x00840016, 0x0084001c, 0xffff0010, 0x00ff0001, 0x00840031 } },
    { "output.L2.current", VCONV_NONE, 1, 0, 6, { 0x00840004, 0x00840016, 0x0084001c, 0xffff0010, 0x00ff0002, 0x00840031 } },
    { "output.L3.current", VCONV_NONE, 1, 0, 6, { 0x00840004, 0x00840016, 0x0084001c, 0xffff0010, 0x00ff0003, 0x00840031 } },
    { "output.current.nominal", VCONV_NONE, 2, 0, 4, { 0x00840004, 0x0084001e, 0x00ff0004, 0x00840041 } },
    { "output.frequency", VCONV_NONE, 1, 0, 4, { 0x00840004, 0x00840016, 0x0084001c, 0x00840032 } },
    { "output.frequency.nominal", VCONV_NONE, 0, 2, 4, { 0x00840004, 0x0084001e, 0x00ff0004, 0x00840042 } },
    { "outlet.id", VCONV_NONE, 0, 2, 5, { 0x00840004, 0x00840018, 0x00840020, 0x00ff0001, 0x00840021 } },
    { "outlet.switchable", VCONV_YESNO, 0, 2, 6, { 0x00840004, 0x00840018, 0x00840020, 0x00ff0001, 0x00840002, 0x0084006c } },
    { "outlet.power", VCONV_NONE, 0, 0, 5, { 0x00840004, 0x00840018, 0x00840020, 0x00ff0001, 0x00840033 } },
    { "outlet.realpower", VCONV_NONE, 0, 0, 5, { 0x00840004, 0x00840018, 0x00840020, 0x00ff0001, 0x00840034 } },
    { "outlet.current", VCONV_NONE, 2, 0, 5, { 0x00840004, 0x00840018, 0x00840020, 0x00ff0001, 0x00840031 } },
    { "outlet.powerfactor", VCONV_NONE, 2, 0, 5, { 0x00840004, 0x00840018, 0x00840020, 0x00ff0001, 0xffff0069 } },
    { "outlet.1.id", VCONV_NONE, 0, 2, 5, { 0x00840004, 0x00840018, 0x00840020, 0x00ff0002, 0x00840021 } },
    { "outlet.1.switchable", VCONV_YESNO, 0, 2, 6, { 0x00840004, 0x00840018, 0x00840020, 0x00ff0002, 0x00840002, 0x0084006c } },
    { "outlet.1.status", VCONV_ONOFF, 0, 0, 6, { 0x00840004, 0x00840018, 0x00840020, 0x00ff0002, 0x00840002, 0x0084006b } },
    { "outlet.1.designator", VCONV_STRINGID, 0, 2, 5, { 0x00840004, 0x00840018, 0x00840020, 0x00ff0002, 0xffff00ba } },
    { "outlet.1.status", VCONV_ONOFF, 0, 0, 4, { 0x00840004, 0x00840024, 0x00840002, 0x008500d0 } },
    { "outlet.1.autoswitch.charge.low", VCONV_NONE, 0, 1, 5, { 0x00840004, 0x00840018, 0x00840020, 0x00ff0002, 0x00850029 } },
    { "outlet.1.delay.shutdown", VCONV_NONE, 0, 1, 5, { 0x00840004, 0x00840018, 0x00840020, 0x00ff0002, 0xffff005d } },
    { "outlet.1.delay.start", VCONV_NONE, 0, 1, 5, { 0x00840004, 0x00840018, 0x00840020, 0x00ff0002, 0xffff005e } },
    { "outlet.1.power", VCONV_NONE, 0, 0, 5, { 0x00840004, 0x00840018, 0x00840020, 0x00ff0002, 0x00840033 } },
    { "outlet.1.realpower", VCONV_NONE, 0, 0, 5, { 0x00840004, 0x00840018, 0x00840020, 0x00ff0002, 0x00840034 } },
    { "outlet.1.current", VCONV_NONE, 2, 0, 5, { 0x00840004, 0x00840018, 0x00840020, 0x00ff0002, 0x00840031 } },
    { "outlet.1.powerfactor", VCONV_NONE, 2, 0, 5, { 0x00840004, 0x00840018, 0x00840020, 0x00ff0002, 0xffff0069 } },
    { "outlet.2.id", VCONV_NONE, 0, 2, 5, { 0x00840004, 0x00840018, 0x00840020, 0x00ff0003, 0x00840021 } },
    { "outlet.2.switchable", VCONV_YESNO, 0, 0, 6, { 0x00840004, 0x00840018, 0x00840020, 0x00ff0003, 0x00840002, 0x0084006c } },
    { "outlet.2.status", VCONV_ONOFF, 0, 0, 6, { 0x00840004, 0x00840018, 0x00840020, 0x00ff0003, 0x00840002, 0x0084006b } },
    { "outlet.2.autoswitch.charge.low", VCONV_NONE, 0, 1, 5, { 0x00840004, 0x00840018, 0x00840020, 0x00ff0003, 0x00850029 } },
    { "outlet.2.delay.shutdown", VCONV_NONE, 0, 1, 5, { 0x00840004, 0x00840018, 0x00840020, 0x00ff0003, 0xffff005d } },
    { "outlet.2.delay.start", VCONV_NONE, 0, 1, 5, { 0x00840004, 0x00840018, 0x00840020, 0x00ff0003, 0xffff005e } },
    { "outlet.2.power", VCONV_NONE, 0, 0, 5, { 0x00840004, 0x00840018, 0x00840020, 0x00ff0003, 0x00840033 } },
    { "outlet.2.realpower", VCONV_NONE, 0, 0, 5, { 0x00840004, 0x00840018, 0x00840020, 0x00ff0003, 0x00840034 } },
    { "outlet.2.current", VCONV_NONE, 2, 0, 5, { 0x00840004, 0x00840018, 0x00840020, 0x00ff0003, 0x00840031 } },
    { "outlet.2.powerfactor", VCONV_NONE, 2, 0, 5, { 0x00840004, 0x00840018, 0x00840020, 0x00ff0003, 0xffff0069 } },
    { "outlet.3.id", VCONV_NONE, 0, 2, 5, { 0x00840004, 0x00840018, 0x00840020, 0x00ff0004, 0x00840021 } },
    { "outlet.3.switchable", VCONV_YESNO, 0, 0, 6, { 0x00840004, 0x00840018, 0x00840020, 0x00ff0004, 0x00840002, 0x0084006c } },
    { "outlet.3.status", VCONV_ONOFF, 0, 0, 6, { 0x00840004, 0x00840018, 0x00840020, 0x00ff0004, 0x00840002, 0x0084006b } },
    { "outlet.3.autoswitch.charge.low", VCONV_NONE, 0, 1, 5, { 0x00840004, 0x00840018, 0x00840020, 0x00ff0004, 0x00850029 } },
    { "outlet.3.delay.shutdown", VCONV_NONE, 0, 1, 5, { 0x00840004, 0x00840018, 0x00840020, 0x00ff0004, 0xffff005d } },
    { "outlet.3.delay.start", VCONV_NONE, 0, 1, 5, { 0x00840004, 0x00840018, 0x00840020, 0x00ff0004, 0xffff005e } },
    { "outlet.3.power", VCONV_NONE, 0, 0, 5, { 0x00840004, 0x00840018, 0x00840020, 0x00ff0004, 0x00840033 } },
    { "outlet.3.realpower", VCONV_NONE, 0, 0, 5, { 0x00840004, 0x00840018, 0x00840020, 0x00ff0004, 0x00840034 } },
    { "outlet.3.current", VCONV_NONE, 2, 0, 5, { 0x00840004, 0x00840018, 0x00840020, 0x00ff0004, 0x00840031 } },
    { "outlet.3.powerfactor", VCONV_NONE, 2, 0, 5, { 0x00840004, 0x00840018, 0x00840020, 0x00ff0004, 0xffff0069 } },
    { "battery.charge.low", VCONV_NONE, 0, 1, 3, { 0x00840004, 0x00840024, 0x00850029 } },
    { "battery.charge.warning", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00840024, 0x0085008c } },
    { "battery.runtime", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00840012, 0x00850068 } },
    { "battery.runtime.low", VCONV_NONE, 0, 1, 3, { 0x00840004, 0x00840012, 0x0085002a } },
    { "battery.runtime.low", VCONV_NONE, 0, 1, 3, { 0x00840004, 0x00840024, 0x0085002a } },
    { "battery.voltage", VCONV_NONE, 1, 0, 3, { 0x00840004, 0x00840012, 0x00840030 } },
    { "battery.voltage", VCONV_NONE, 1, 0, 3, { 0x00840004, 0x00840024, 0x00840030 } },
    { "battery.voltage.nominal", VCONV_NONE, 1, 0, 3, { 0x00840004, 0x00840012, 0x00840040 } },
    { "battery.voltage.nominal", VCONV_NONE, 1, 0, 3, { 0x00840004, 0x00840024, 0x00840040 } },
    { "battery.temperature", VCONV_KELVIN, 0, 0, 3, { 0x00840004, 0x00840012, 0x00840036 } },
    { "battery.type", VCONV_STRINGID, 0, 0, 3, { 0x00840004, 0x00840024, 0x00850089 } },
    { "battery.mfr.date", VCONV_DATE, 0, 1, 3, { 0x00840004, 0x00840012, 0x00850085 } },
    { "ups.load", VCONV_NONE, 1, 0, 3, { 0x00840004, 0x0084001c, 0x00840035 } },
    { "ups.load", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00840016, 0x00840035 } },
    { "ups.timer.start", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x0084001c, 0x00840056 } },
    { "ups.timer.shutdown", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x0084001c, 0x00840057 } },
    { "ups.timer.reboot", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x0084001c, 0x00840055 } },
    { "ups.timer.start", VCONV_NONE, 0, 0, 3, { 0x00840004, 0xff860005, 0xff86007e } },
    { "ups.timer.shutdown", VCONV_NONE, 0, 0, 3, { 0x00840004, 0xff860005, 0xff86007d } },
    { "ups.timer.reboot", VCONV_NONE, 0, 0, 3, { 0x00840004, 0xff860005, 0xff86007c } },
    { "ups.test.result", VCONV_TEST, 0, 0, 3, { 0x00840004, 0x00840012, 0x00840058 } },
    { "ups.beeper.status", VCONV_BEEPER, 0, 0, 3, { 0x00840004, 0x00840024, 0x0084005a } },
    { "ups.mfr.date", VCONV_DATE, 0, 0, 2, { 0x00840004, 0x00850085 } },
    { "ups.mfr.date", VCONV_DATE, 0, 0, 3, { 0x00840004, 0x00840024, 0x00850085 } },
    { "ups.realpower.nominal", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00840016, 0x00840044 } },
    { "ups.realpower.nominal", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x0084001c, 0x00840044 } },
    { "input.voltage", VCONV_NONE, 1, 0, 3, { 0x00840004, 0x0084001a, 0x00840030 } },
    { "input.voltage.nominal", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x0084001a, 0x00840040 } },
    { "input.transfer.low", VCONV_NONE, 0, 1, 3, { 0x00840004, 0x0084001c, 0x00840053 } },
    { "input.transfer.high", VCONV_NONE, 0, 1, 3, { 0x00840004, 0x0084001c, 0x00840054 } },
    { "input.transfer.low", VCONV_NONE, 0, 1, 3, { 0x00840004, 0x0084001a, 0x00840053 } },
    { "input.transfer.high", VCONV_NONE, 0, 1, 3, { 0x00840004, 0x0084001a, 0x00840054 } },
    { "output.voltage", VCONV_NONE, 1, 0, 3, { 0x00840004, 0x0084001c, 0x00840030 } },
    { "output.voltage.nominal", VCONV_NONE, 1, 0, 3, { 0x00840004, 0x0084001c, 0x00840040 } },
    { "output.current", VCONV_NONE, 2, 0, 3, { 0x00840004, 0x0084001c, 0x00840031 } },
    { "output.frequency", VCONV_NONE, 1, 0, 3, { 0x00840004, 0x0084001c, 0x00840032 } },
    { "ambient.temperature", VCONV_KELVIN, 0, 0, 4, { 0x00840004, 0xff860006, 0xff860007, 0x00840036 } },
    { "ambient.humidity", VCONV_NONE, 1, 0, 4, { 0x00840004, 0xff860006, 0xff860007, 0x00840037 } },
    { "battery.voltage.nominal", VCONV_NONE, 2, 0, 3, { 0x00840004, 0x00840024, 0x00840040 } },
    { "battery.voltage", VCONV_NONE, 2, 0, 3, { 0x00840004, 0x00840024, 0x00840030 } },
    { "battery.charge.warning", VCONV_NONE, 0, 1, 3, { 0x00840004, 0x00840024, 0x0085008c } },
    { "battery.charge", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00860010, 0x00860039 } },
    { "battery.charge.low", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00840024, 0x00850029 } },
    { "battery.voltage", VCONV_DIV10, 0, 0, 3, { 0x00840004, 0x00860010, 0x00860030 } },
    { "battery.voltage.nominal", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00860026, 0x00860044 } },
    { "input.frequency", VCONV_DIV10, 0, 0, 4, { 0x00840004, 0x0086002a, 0x0086001a, 0x00860032 } },
    { "input.frequency.nominal", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00860026, 0x00860042 } },
    { "input.transfer.high", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00860026, 0x00860054 } },
    { "input.transfer.high.max", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00860026, 0x0086005d } },
    { "input.transfer.high.min", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00860026, 0x0086005e } },
    { "input.transfer.low", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00860026, 0x00860053 } },
    { "input.transfer.low.max", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00860026, 0x0086005b } },
    { "input.transfer.low.min", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00860026, 0x0086005c } },
    { "input.voltage", VCONV_DIV10, 0, 0, 4, { 0x00840004, 0x0086002a, 0x0086001a, 0x00860030 } },
    { "input.voltage.nominal", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00860026, 0x00860040 } },
    { "output.frequency", VCONV_DIV10, 0, 0, 4, { 0x00840004, 0x0086002a, 0x0086001c, 0x00860032 } },
    { "output.voltage", VCONV_DIV10, 0, 0, 4, { 0x00840004, 0x0086002a, 0x0086001c, 0x00860030 } },
    { "ups.beeper.status", VCONV_BEEPER, 0, 0, 3, { 0x00840004, 0x00860027, 0x0086005a } },
    { "ups.timer.start", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00860027, 0x00860056 } },
    { "ups.timer.shutdown", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00860027, 0x00860057 } },
    { "ups.timer.reboot", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00860027, 0x00860055 } },
    { "ups.load", VCONV_NONE, 0, 0, 4, { 0x00840004, 0x0086002a, 0x0086001c, 0x00860035 } },
    { "ups.load.high", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00860026, 0x00860045 } },
    { "ups.power.nominal", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00860026, 0x00860043 } },
    { "ups.serial", VCONV_STRINGID, 0, 0, 3, { 0x00840004, 0x00840024, 0x008400ff } },
    { "input.frequency", VCONV_DIV10, 0, 0, 3, { 0x00840004, 0x0084001a, 0x00840032 } },
    { "ups.load", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x0084001c, 0x00840035 } },
    { "input.voltage.nominal", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x0084001e, 0x00840040 } },
    { "input.frequency", VCONV_DIV100, 0, 0, 4, { 0x00840004, 0x00840016, 0x0084001a, 0x00840032 } },
    { "output.voltage.nominal", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x0084001e, 0x00840040 } },
    { "output.frequency", VCONV_DIV100, 0, 0, 4, { 0x00840004, 0x00840016, 0x0084001c, 0x00840032 } },
    { "ups.load", VCONV_NONE, 0, 0, 4, { 0x00840004, 0x00840018, 0x00840020, 0x00840035 } },
    { "battery.voltage.nominal", VCONV_NONE, 0, 0, 4, { 0x00840004, 0x00840010, 0x00840012, 0x00840040 } },
    { "battery.capacity", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x0084001e, 0x00840043 } },
    { "battery.mfr.date", VCONV_STRINGID, 0, 0, 3, { 0x00840004, 0x00840024, 0x0085008f } },
    { "battery.charge", VCONV_CPS_BATTCHARGE, 0, 0, 3, { 0x00840004, 0x00840024, 0x00850066 } },
    { "battery.voltage.nominal", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00840024, 0x00840040 } },
    { "battery.voltage", VCONV_CPS_BATTVOLT, 0, 0, 3, { 0x00840004, 0x00840024, 0x00840030 } },
    { "ups.test.result", VCONV_TEST, 0, 0, 3, { 0x00840004, 0x0084001c, 0x00840058 } },
    { "ups.power", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x0084001c, 0x00840033 } },
    { "ups.power.nominal", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x0084001c, 0x00840043 } },
    { "ups.realpower", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x0084001c, 0x00840034 } },
    { "ups.firmware", VCONV_STRINGID, 0, 2, 3, { 0x00840004, 0x00840024, 0xff0100d0 } },
    { "input.frequency", VCONV_CPS_INFREQ, 1, 0, 3, { 0x00840004, 0x0084001a, 0x00840032 } },
    { "output.frequency", VCONV_CPS_OUTFREQ, 1, 0, 3, { 0x00840004, 0x0084001c, 0x00840032 } },
    { "output.voltage.nominal", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x0084001c, 0x00840040 } },
    { "input.voltage.nominal", VCONV_NONE, 1, 1, 4, { 0x00840004, 0x00840024, 0x0084001a, 0x00840040 } },
    { "input.voltage", VCONV_NONE, 1, 0, 4, { 0x00840004, 0x00840024, 0x0084001a, 0x00840030 } },
    { "input.voltage", VCONV_NONE, 1, 0, 4, { 0x00840004, 0x00840016, 0x0084001a, 0x00840030 } },
    { "input.transfer.low", VCONV_NONE, 1, 0, 4, { 0x00840004, 0x00840016, 0x0084001c, 0x00840053 } },
    { "input.transfer.high", VCONV_NONE, 1, 0, 4, { 0x00840004, 0x00840016, 0x0084001c, 0x00840054 } },
    { "input.transfer.low.min", VCONV_NONE, 1, 2, 4, { 0x00840004, 0x00840016, 0x0084001c, 0xffff0058 } },
    { "input.transfer.low.max", VCONV_NONE, 1, 2, 4, { 0x00840004, 0x00840016, 0x0084001c, 0xffff0057 } },
    { "input.transfer.high.min", VCONV_NONE, 1, 2, 4, { 0x00840004, 0x00840016, 0x0084001c, 0xffff005a } },
    { "input.transfer.high.max", VCONV_NONE, 1, 2, 4, { 0x00840004, 0x00840016, 0x0084001c, 0xffff0059 } },
    { "input.frequency", VCONV_NONE, 1, 0, 4, { 0x00840004, 0x00840016, 0x0084001a, 0x00840032 } },
    { "battery.voltage.nominal", VCONV_NONE, 1, 2, 4, { 0x00840004, 0x00840010, 0x00840012, 0x00840040 } },
    { "battery.voltage", VCONV_NONE, 1, 0, 4, { 0x00840004, 0x00840010, 0x00840012, 0x00840030 } },
    { "battery.charge", VCONV_NONE, 0, 0, 4, { 0x00840004, 0x00840010, 0x00840012, 0x00850066 } },
    { "battery.temperature", VCONV_KELVIN, 0, 0, 3, { 0x00840004, 0x00840010, 0x00840036 } },
    { "battery.capacity", VCONV_NONE, 0, 1, 3, { 0x00840004, 0x00840024, 0x00850083 } },
    { "battery.capacity", VCONV_NONE, 0, 1, 3, { 0x00840004, 0x00840024, 0x00850067 } },
    { "output.voltage.nominal", VCONV_NONE, 1, 1, 3, { 0x00840004, 0x0084001e, 0x00840040 } },
    { "output.frequency.nominal", VCONV_NONE, 1, 1, 3, { 0x00840004, 0x0084001e, 0x00840042 } },
    { "output.current", VCONV_NONE, 1, 0, 4, { 0x00840004, 0x00840016, 0x0084001c, 0x00840031 } },
    { "ups.test.result", VCONV_TEST, 0, 0, 3, { 0x00840004, 0x00840010, 0x00840058 } },
    { "ups.start.auto", VCONV_YESNO, 0, 0, 4, { 0x00840004, 0xffff0010, 0x00ff0001, 0xffff009c } },
    { "ups.power.nominal", VCONV_NONE, 0, 2, 3, { 0x00840004, 0x0084001e, 0x00840043 } },
    { "ups.realpower", VCONV_NONE, 1, 0, 4, { 0x00840004, 0x00840018, 0x00840020, 0x00840034 } },
    { "ups.realpower", VCONV_NONE, 1, 0, 4, { 0x00840004, 0x00840016, 0x0084001c, 0x00840034 } },
    { "ups.load", VCONV_NONE, 1, 0, 4, { 0x00840004, 0x00840018, 0x00840020, 0x00840035 } },
    { "ups.delay.start", VCONV_NONE, 0, 0, 4, { 0x00840004, 0x00840018, 0x00840020, 0xffff0081 } },
    { "ups.timer.start", VCONV_NONE, 0, 0, 4, { 0x00840004, 0x00840018, 0x00840020, 0x00840056 } },
    { "ups.timer.shutdown", VCONV_NONE, 0, 0, 4, { 0x00840004, 0x00840018, 0x00840020, 0x00840057 } },
    { "ups.timer.reboot", VCONV_NONE, 0, 0, 4, { 0x00840004, 0x00840018, 0x00840020, 0x00840055 } },
    { "ups.power.nominal", VCONV_NONE, 0, 2, 4, { 0x00840004, 0x0084001e, 0x00ff0004, 0x00840044 } },
    { "battery.voltage.nominal", VCONV_NONE, 1, 1, 3, { 0x00840004, 0x00840024, 0x00840040 } },
    { "battery.capacity.nominal", VCONV_NONE, 0, 1, 3, { 0x00840004, 0x00840024, 0x00850083 } },
    { "experimental.ups.powersummary.ioeminformation", VCONV_STRINGID, 0, 2, 3, { 0x00840004, 0x00840024, 0x0085008f } },
    { "experimental.ups.powersummary.presentstatus.shutdownrequested", VCONV_NONE, 0, 0, 4, { 0x00840004, 0x00840024, 0x00840002, 0x00840068 } },
    { "experimental.ups.powersummary.presentstatus.voltagenotregulated", VCONV_NONE, 0, 0, 4, { 0x00840004, 0x00840024, 0x00840002, 0x008500db } },
    { "experimental.ups.powersummary.rechargeable", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00840024, 0x0085008b } },
    { "experimental.battery.batteryid", VCONV_NONE, 0, 0, 4, { 0x00840004, 0x00840010, 0x00840012, 0x00840013 } },
    { "experimental.battery.systemid", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00840010, 0x00840011 } },
    { "experimental.battery.chargerid", VCONV_NONE, 0, 0, 4, { 0x00840004, 0x00840010, 0x00840014, 0x00840015 } },
    { "experimental.battery.input_flowid", VCONV_NONE, 0, 0, 4, { 0x00840004, 0x00840010, 0x0084001a, 0x0084001f } },
    { "experimental.battery.input_id", VCONV_NONE, 0, 0, 4, { 0x00840004, 0x00840010, 0x0084001a, 0x0084001b } },
    { "experimental.battery.output_flowid", VCONV_NONE, 0, 0, 4, { 0x00840004, 0x00840010, 0x0084001c, 0x0084001f } },
    { "experimental.battery.output_id", VCONV_NONE, 0, 0, 4, { 0x00840004, 0x00840010, 0x0084001c, 0x0084001d } },
    { "ups.temperature", VCONV_KELVIN, 0, 0, 3, { 0x00840004, 0x00000000, 0xff000040 } },
    { "battery.temperature", VCONV_KELVIN, 0, 0, 3, { 0x00840004, 0x00000000, 0xff000041 } },
    { "output.powerfactor", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00000000, 0xff000042 } },
    { "experimental.control.ups_on", VCONV_NONE, 0, 0, 4, { 0x00840004, 0x00000000, 0xff000043, 0xff000044 } },
    { "experimental.control.clear_fault", VCONV_NONE, 0, 0, 4, { 0x00840004, 0x00000000, 0xff000043, 0xff000045 } },
    { "experimental.control.clear_battery_fault", VCONV_NONE, 0, 0, 4, { 0x00840004, 0x00000000, 0xff000043, 0xff000046 } },
    { "experimental.control.epo_blocked", VCONV_NONE, 0, 0, 4, { 0x00840004, 0x00000000, 0xff000050, 0xff000051 } },
    { "experimental.control.green_mode", VCONV_NONE, 0, 0, 4, { 0x00840004, 0x00000000, 0xff000050, 0xff000052 } },
    { "experimental.control.button_sound", VCONV_NONE, 0, 0, 4, { 0x00840004, 0x00000000, 0xff000050, 0xff000053 } },
    { "experimental.control.audible_alarm", VCONV_NONE, 0, 0, 4, { 0x00840004, 0x00000000, 0xff000050, 0xff000054 } },
    { "output.voltage", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00000000, 0xff000060 } },
    { "experimental.config.overload_clearance_threshold", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00000000, 0xff000066 } },
    { "experimental.config.stb_charge", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00000000, 0xff000067 } },
    { "battery.packs.external", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00000000, 0xff000068 } },
    { "experimental.statistics.mains_loss_counter", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00000000, 0xff000069 } },
    { "experimental.statistics.lowering_AVR_trigger_counter", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00000000, 0xff00006a } },
    { "experimental.statistics.rising_AVR_trigger_counter", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00000000, 0xff00006b } },
    { "experimental.statistics.overload_counter", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00000000, 0xff00006c } },
    { "experimental.statistics.short_circuit_counter", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00000000, 0xff00006d } },
    { "experimental.statistics.discharge_counter", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00000000, 0xff00006e } },
    { "experimental.statistics.overheat_counter", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00000000, 0xff00006f } },
    { "experimental.statistics.mains_operation_time", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00000000, 0xff000070 } },
    { "experimental.statistics.autonomous_operation_time", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00000000, 0xff000071 } },
    { "experimental.statistics.overload_operation_time", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00000000, 0xff000072 } },
    { "experimental.networkcard.config_dhcp_enabled", VCONV_NONE, 0, 0, 4, { 0x00840004, 0x00000000, 0xff000080, 0xff000081 } },
    { "experimental.networkcard.config_ethernet_enabled", VCONV_NONE, 0, 0, 4, { 0x00840004, 0x00000000, 0xff000080, 0xff000082 } },
    { "experimental.networkcard.config_http_enabled", VCONV_NONE, 0, 0, 4, { 0x00840004, 0x00000000, 0xff000080, 0xff000083 } },
    { "experimental.networkcard.config_snmp_enabled", VCONV_NONE, 0, 0, 4, { 0x00840004, 0x00000000, 0xff000080, 0xff000084 } },
    { "experimental.networkcard.config_snmp_trap_enabled", VCONV_NONE, 0, 0, 4, { 0x00840004, 0x00000000, 0xff000080, 0xff000085 } },
    { "experimental.networkcard.config_readonly", VCONV_NONE, 0, 0, 4, { 0x00840004, 0x00000000, 0xff000080, 0xff000086 } },
    { "experimental.networkcard.config_restart_eth", VCONV_NONE, 0, 0, 4, { 0x00840004, 0x00000000, 0xff000080, 0xff00008b } },
    { "ups.realpower.nominal", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x0084001e, 0x00840044 } },
    { "ups.power.nominal", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x0084001e, 0x00840043 } },
    { "output.frequency.nominal", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x0084001e, 0x00840042 } },
    { "experimental.ups.flow_id", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x0084001e, 0x0084001f } },
    { "outlet.1.id", VCONV_NONE, 0, 0, 4, { 0x00840004, 0x00840018, 0x00840020, 0x00840021 } },
    { "experimental.outlet.1.present", VCONV_YESNO, 0, 0, 5, { 0x00840004, 0x00840018, 0x00840020, 0x00840002, 0x00840060 } },
    { "outlet.1.switchable", VCONV_YESNO, 0, 0, 5, { 0x00840004, 0x00840018, 0x00840020, 0x00840002, 0x0084006c } },
    { "outlet.1.status", VCONV_NONE, 0, 0, 5, { 0x00840004, 0x00840018, 0x00840020, 0x00840002, 0x0084006b } },
    { "experimental.outlet.1.undefined", VCONV_NONE, 0, 0, 5, { 0x00840004, 0x00840018, 0x00840020, 0x00840002, 0x00840000 } },
    { "experimental.outlet.1.system_id", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00840018, 0x00840019 } },
    { "experimental.outlet.1.switch_off_control", VCONV_NONE, 0, 0, 4, { 0x00840004, 0x00840018, 0x00840020, 0x00840051 } },
    { "experimental.outlet.1.switch_on_control", VCONV_NONE, 0, 0, 4, { 0x00840004, 0x00840018, 0x00840020, 0x00840050 } },
    { "experimental.powerconverter.input_flow_id", VCONV_NONE, 0, 0, 4, { 0x00840004, 0x00840016, 0x0084001a, 0x0084001f } },
    { "input.frequency", VCONV_NONE, 0, 0, 4, { 0x00840004, 0x00840016, 0x0084001a, 0x00840032 } },
    { "experimental.powerconverter.input_id", VCONV_NONE, 0, 0, 4, { 0x00840004, 0x00840016, 0x0084001a, 0x0084001b } },
    { "input.voltage", VCONV_NONE, 0, 0, 4, { 0x00840004, 0x00840016, 0x0084001a, 0x00840030 } },
    { "output.current", VCONV_NONE, 0, 0, 4, { 0x00840004, 0x00840016, 0x0084001c, 0x00840031 } },
    { "experimental.powerconverter.output_flowid", VCONV_NONE, 0, 0, 4, { 0x00840004, 0x00840016, 0x0084001c, 0x0084001f } },
    { "output.frequency", VCONV_NONE, 0, 0, 4, { 0x00840004, 0x00840016, 0x0084001c, 0x00840032 } },
    { "experimental.powerconverter.output_id", VCONV_NONE, 0, 0, 4, { 0x00840004, 0x00840016, 0x0084001c, 0x0084001d } },
    { "ups.load", VCONV_NONE, 0, 0, 4, { 0x00840004, 0x00840016, 0x0084001c, 0x00840035 } },
    { "output.voltage", VCONV_NONE, 0, 0, 4, { 0x00840004, 0x00840016, 0x0084001c, 0x00840030 } },
    { "experimental.powersummary.capacity_granularity_1", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00840024, 0x0085008d } },
    { "experimental.powersummary.capacity_granularity_2", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00840024, 0x0085008e } },
    { "experimental.powersummary.capacity_mode", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00840024, 0x0085002c } },
    { "battery.capacity", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00840024, 0x00850083 } },
    { "experimental.powersummary.flow_id", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00840024, 0x0084001f } },
    { "battery.capacity", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00840024, 0x00850067 } },
    { "battery.type", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00840024, 0x00850089 } },
    { "experimental.powersummary.rechargeable", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00840024, 0x0085008b } },
    { "battery.voltage", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00840024, 0x00840030 } },
    { "device.mfr", VCONV_STRINGID, 0, 2, 3, { 0x00840004, 0x00840024, 0x008400fd } },
    { "device.model", VCONV_STRINGID, 0, 2, 3, { 0x00840004, 0x00840024, 0x008400fe } },
    { "device.serial", VCONV_STRINGID, 0, 2, 3, { 0x00840004, 0x00840024, 0x008400ff } },
    { "battery.capacity.design", VCONV_NONE, 0, 2, 3, { 0x00840004, 0x00840024, 0x00850083 } },
    { "battery.charge.low", VCONV_NONE, 0, 2, 3, { 0x00840004, 0x00840024, 0x0085008c } },
    { "battery.capacity.full", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00840024, 0x00850067 } },
    { "input.transfer.high", VCONV_NONE, 0, 2, 4, { 0x00840004, 0x00840016, 0x0084001c, 0x00840054 } },
    { "input.transfer.low", VCONV_NONE, 0, 2, 4, { 0x00840004, 0x00840016, 0x0084001c, 0x00840053 } },
    { "output.voltage.nominal", VCONV_NONE, 0, 2, 4, { 0x00840004, 0x0084001e, 0x00ff0004, 0x00840040 } },
    { "battery.voltage.nominal", VCONV_NONE, 1, 2, 3, { 0x00840004, 0x00840024, 0x00840040 } },
    { "input.voltage", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x0084001a, 0x00840030 } },
    { "input.transfer.high", VCONV_NONE, 0, 2, 3, { 0x00840004, 0x0084001a, 0x00840054 } },
    { "input.transfer.low", VCONV_NONE, 0, 2, 3, { 0x00840004, 0x0084001a, 0x00840053 } },
    { "input.voltage.nominal", VCONV_NONE, 0, 2, 3, { 0x00840004, 0x0084001a, 0x00840040 } },
    { "input.voltage.nominal", VCONV_NONE, 0, 2, 3, { 0x00840004, 0x0084001e, 0x00840040 } },
    { "battery.voltage.nominal", VCONV_DIV10, 0, 2, 3, { 0x00840004, 0x00840024, 0x00840040 } },
    { "battery.voltage.nominal", VCONV_NONE, 0, 2, 4, { 0x00840004, 0x00840010, 0x00840012, 0x00840040 } },
    { "battery.voltage", VCONV_DIV10, 0, 0, 3, { 0x00840004, 0x00840024, 0x00840030 } },
    { "battery.charge.warning", VCONV_NONE, 0, 2, 3, { 0x00840004, 0x00840024, 0x0085008c } },
    { "output.voltage", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x0084001c, 0x00840030 } },
    { "output.frequency", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x0084001c, 0x00840032 } },
    { "ups.realpower.nominal", VCONV_NONE, 0, 2, 3, { 0x00840004, 0x0084001c, 0x00840044 } },
    { "ups.realpower.nominal", VCONV_NONE, 0, 2, 3, { 0x00840004, 0x0084001e, 0x00840043 } },
    { "experimental.battery.capacity", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00840024, 0x00850067 } },
    { "experimental.battery.capacity.nominal", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00840024, 0x00850083 } },
    { "ups.power.nominal", VCONV_NONE, 0, 1, 4, { 0x00840004, 0x0084001e, 0x00ff0004, 0x00840043 } },
    { "output.voltage.nominal", VCONV_NONE, 0, 1, 4, { 0x00840004, 0x0084001e, 0x00ff0004, 0x00840040 } },
    { "output.frequency", VCONV_NONE, 2, 0, 4, { 0x00840004, 0x00840016, 0x0084001c, 0x00840032 } },
    { "output.frequency.nominal", VCONV_NONE, 0, 1, 4, { 0x00840004, 0x0084001e, 0x00ff0004, 0x00840042 } },
    { "output.transfer.high", VCONV_NONE, 1, 1, 4, { 0x00840004, 0x00840016, 0x0084001c, 0x00840054 } },
    { "output.transfer.low", VCONV_NONE, 1, 1, 4, { 0x00840004, 0x00840016, 0x0084001c, 0x00840053 } },
    { "input.frequency", VCONV_NONE, 2, 0, 5, { 0x00840004, 0x00840016, 0x0084001a, 0x00ff0001, 0x00840032 } },
    { "input.transfer.low", VCONV_NONE, 0, 1, 4, { 0x00840004, 0x00840016, 0x0084001c, 0xffff0057 } },
    { "input.transfer.high", VCONV_NONE, 0, 1, 4, { 0x00840004, 0x00840016, 0x0084001c, 0xffff0058 } },
    { "input.frequency.transfer.low", VCONV_NONE, 0, 1, 4, { 0x00840004, 0x00840016, 0x0084001c, 0xffff00f9 } },
    { "input.frequency.transfer.high", VCONV_NONE, 0, 1, 4, { 0x00840004, 0x00840016, 0x0084001c, 0xffff00f8 } },
    { "battery.mfr.date", VCONV_STRINGID, 0, 2, 3, { 0x00840004, 0x00840024, 0x0085008f } },
    { "battery.current", VCONV_NONE, 3, 0, 3, { 0x00840004, 0x00840024, 0x00840031 } },
    { "battery.capacity", VCONV_NONE, 0, 2, 3, { 0x00840004, 0x00840024, 0x00850083 } },
    { "battery.charge", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00840012, 0x00850066 } },
    { "battery.mfr.date", VCONV_DATE, 0, 2, 3, { 0x00840004, 0x00840012, 0x00850085 } },
    { "ups.date", VCONV_DATE, 0, 2, 3, { 0x00840004, 0x00840024, 0x00850085 } },
    { "input.frequency", VCONV_NONE, 1, 0, 3, { 0x00840004, 0x0084001a, 0x00840032 } },
    { "output.voltage.nominal", VCONV_NONE, 0, 2, 3, { 0x00840004, 0x0084001c, 0x00840040 } },
    { "ups.serial", VCONV_STRINGID, 0, 0, 2, { 0x00020004, 0x00020086 } },
    { "ups.mfr", VCONV_STRINGID, 0, 0, 2, { 0x00020004, 0x00020087 } },
    { "ups.mfr.date", VCONV_DATE, 0, 0, 2, { 0x00020004, 0x00020085 } },
    { "battery.temperature", VCONV_NONE, 0, 0, 3, { 0x00020004, 0x00020010, 0x00020036 } },
    { "battery.temperature", VCONV_NONE, 1, 0, 3, { 0x00840004, 0x00840012, 0x00840036 } },
    { "battery.charge", VCONV_NONE, 0, 0, 3, { 0x00020004, 0x00020010, 0x00020030 } },
    { "input.frequency", VCONV_NONE, 0, 0, 4, { 0x00020004, 0x00020016, 0x0002001a, 0x00020032 } },
    { "ups.load", VCONV_NONE, 0, 0, 4, { 0x00020004, 0x00020016, 0x0002001c, 0x00020035 } },
    { "output.frequency", VCONV_NONE, 0, 0, 4, { 0x00020004, 0x00020016, 0x0002001c, 0x00020032 } },
    { "ups.test.result", VCONV_TEST, 0, 0, 3, { 0x00020004, 0x00020016, 0x00020058 } },
    { "ups.delay.shutdown", VCONV_NONE, 0, 0, 3, { 0x00020004, 0x00020016, 0x00020057 } },
    { "ups.delay.start", VCONV_NONE, 0, 0, 3, { 0x00020004, 0x00020016, 0x00020056 } },
    { "ups.realpower.nominal", VCONV_NONE, 0, 0, 4, { 0x00840004, 0x0084001e, 0x00ff0004, 0x00840044 } },
    { "output.voltage.nominal", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x00840024, 0x00840040 } },
    { "device.part", VCONV_STRINGID, 0, 2, 4, { 0x00840004, 0xffff0010, 0x00ff0001, 0xffff007f } },
    { "ups.timer.start", VCONV_NONE, 0, 0, 4, { 0x00840004, 0x00840018, 0x00840020, 0xffff0056 } },
    { "ups.power", VCONV_NONE, 1, 0, 4, { 0x00840004, 0x00840018, 0x00840020, 0x00840033 } },
    { "ups.power", VCONV_NONE, 1, 0, 4, { 0x00840004, 0x00840016, 0x0084001c, 0x00840033 } },
    { "ups.realpower.nominal", VCONV_NONE, 0, 2, 3, { 0x00840004, 0x0084001e, 0x00840044 } },
    { "ups.firmware", VCONV_NONE, 0, 2, 4, { 0x00840004, 0xffff0010, 0x00ff0001, 0xffff007c } },
    { "ups.watchdog.status", VCONV_NONE, 0, 0, 4, { 0x00840004, 0x00840018, 0x00840020, 0xffff0092 } },
    { "ups.load.nominal", VCONV_NONE, 0, 0, 3, { 0x00840004, 0x0084001e, 0x00840045 } },
    { "input.voltage.nominal", VCONV_NONE, 0, 2, 4, { 0x00840004, 0x00840024, 0x0084001a, 0x00840040 } },
    { "input.transfer.low", VCONV_NONE, 1, 1, 4, { 0x00840004, 0x00840016, 0x0084001c, 0x00840053 } },
    { "input.transfer.low.max", VCONV_NONE, 0, 2, 4, { 0x00840004, 0x00840016, 0x0084001c, 0xffff0057 } },
    { "input.transfer.low.min", VCONV_NONE, 0, 2, 4, { 0x00840004, 0x00840016, 0x0084001c, 0xffff0058 } },
    { "input.transfer.high", VCONV_NONE, 1, 1, 4, { 0x00840004, 0x00840016, 0x0084001c, 0x00840054 } },
    { "input.transfer.high.max", VCONV_NONE, 0, 2, 4, { 0x00840004, 0x00840016, 0x0084001c, 0xffff0059 } },
    { "input.transfer.high.min", VCONV_NONE, 0, 2, 4, { 0x00840004, 0x00840016, 0x0084001c, 0xffff005a } },
    { "output.voltage.nominal", VCONV_NONE, 0, 2, 3, { 0x00840004, 0x0084001e, 0x00840040 } },
    { "output.frequency.nominal", VCONV_NONE, 0, 2, 3, { 0x00840004, 0x0084001e, 0x00840042 } },
};
const size_t ups_vartab_row_count = 407;

static const uint16_t s_explore[] = { 0 };
static const uint16_t s_mge[] = { 0, 1, 2, 3, 4, 5, 6, 7, 6, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140 };
static const uint16_t s_apc[] = { 1, 141, 142, 143, 5, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 22, 23, 24, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178 };
static const uint16_t s_arduino[] = { 22, 23, 24, 9, 179, 180, 5, 145, 1, 141, 181, 20, 44, 89 };
static const uint16_t s_belkin[] = { 182, 183, 142, 5, 151, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 164, 204, 205, 1, 206, 207, 208, 209, 210, 211, 212, 213, 214 };
static const uint16_t s_cps[] = { 151, 152, 215, 142, 141, 216, 5, 145, 217, 218, 207, 162, 219, 220, 221, 222, 166, 155, 156, 157, 223, 30, 224, 168, 167, 171, 172, 169, 170, 225, 173, 226 };
static const uint16_t s_delta_ups[] = { 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 1, 239, 141, 181, 240, 5, 9, 241, 242, 243, 244, 89, 101, 245, 162, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255 };
static const uint16_t s_ecoflow[] = { 162, 256, 257, 255, 254, 258, 242, 9, 259, 164, 260, 261, 262, 1, 141, 145, 147, 181 };
static const uint16_t s_ever[] = { 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299, 300, 301, 302, 303, 210, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 315, 316, 36, 31, 317, 318, 319, 320, 321, 322, 323, 324, 325, 326, 327, 328, 329, 20, 330, 1, 6, 5, 331, 23 };
static const uint16_t s_idowell[] = { 332, 333, 334, 335, 1, 3, 336, 337, 5, 9, 22, 23, 20, 35, 338, 339, 89, 147, 340, 341, 102 };
static const uint16_t s_legrand[] = { 342, 343, 344, 339, 345, 346, 347, 348, 349, 1, 350, 3, 351, 352, 207, 212, 353, 354, 28 };
static const uint16_t s_liebert[] = { 180, 1, 355, 356, 5, 151, 20, 357, 25, 28, 89, 358, 359, 360, 361, 362, 44, 363, 364, 365, 366, 367 };
static const uint16_t s_openups[] = { 205, 9, 368, 180, 369, 370, 1, 183, 142, 5 };
static const uint16_t s_powercom[] = { 1, 371, 183, 142, 5, 372, 9, 207, 373, 161, 167, 345, 374, 173, 375, 176, 376, 377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387 };
static const uint16_t s_powervar[] = { 151, 1, 328 };
static const uint16_t s_salicru[] = { 151, 1, 142, 141, 5, 145, 217, 180, 207, 162, 219, 166, 374, 168, 167, 338, 339, 176, 173, 226, 20, 25, 388, 36, 57, 44, 101, 89, 389, 25 };
static const uint16_t s_tripplite[] = { 390, 1, 239, 141, 142, 5, 237, 240, 253, 391, 254, 255, 246, 162, 248, 392, 393, 394, 249, 250, 212, 395, 396, 397, 398, 399, 400, 401, 402, 403, 404, 405, 406 };
static const uint16_t s_common[] = { 1, 3, 5, 6, 9, 20, 22, 23, 24, 25, 28, 30, 31, 35, 36, 44, 57, 89, 101, 102, 141, 142, 145, 147, 151, 152, 155, 156, 157, 161, 162, 164, 166, 167, 168, 169, 170, 171, 172, 173, 176, 180, 181, 183, 205, 207, 210, 212, 217, 219, 226, 237, 239, 240, 242, 246, 248, 249, 250, 253, 254, 255, 328, 338, 339, 345, 374 };

static const uint16_t *const s_lists[] = {
    s_explore,
    s_mge,
    s_apc,
    s_arduino,
    s_belkin,
    s_cps,
    s_delta_ups,
    s_ecoflow,
    s_ever,
    s_idowell,
    s_legrand,
    s_liebert,
    s_openups,
    s_powercom,
    s_powervar,
    s_salicru,
    s_tripplite,
};
static const uint16_t s_list_len[] = {
    0,
    142,
    43,
    14,
    38,
    32,
    37,
    18,
    77,
    21,
    19,
    22,
    10,
    28,
    3,
    30,
    33,
};

const ups_vartab_sub_t ups_vartab_subs[] = {
    { "explore", 0 },
    { "mge", 1 },
    { "apc", 2 },
    { "arduino", 3 },
    { "belkin", 4 },
    { "cps", 5 },
    { "delta_ups", 6 },
    { "ecoflow", 7 },
    { "ever", 8 },
    { "idowell", 9 },
    { "legrand", 10 },
    { "liebert", 11 },
    { "openups", 12 },
    { "powercom", 13 },
    { "powervar", 14 },
    { "salicru", 15 },
    { "tripplite", 16 },
};
const size_t ups_vartab_sub_count = 17;

/* USB IDs each subdriver claims, in NUT's subdriver order: first match wins. */
const ups_vartab_id_t ups_vartab_ids[] = {
    { 0x0463, 0x0001, 1 },  /* mge */
    { 0x0463, 0xffff, 1 },  /* mge */
    { 0x047c, 0xffff, 1 },  /* mge */
    { 0x0592, 0x0004, 1 },  /* mge */
    { 0x03f0, 0x1fe5, 1 },  /* mge */
    { 0x03f0, 0x1fe6, 1 },  /* mge */
    { 0x03f0, 0x1fe7, 1 },  /* mge */
    { 0x03f0, 0x1fe8, 1 },  /* mge */
    { 0x2b2d, 0xffff, 1 },  /* mge */
    { 0x06da, 0xffff, 1 },  /* mge */
    { 0x04b3, 0x0001, 1 },  /* mge */
    { 0x09d6, 0x0001, 1 },  /* mge */
    { 0x051d, 0x0000, 2 },  /* apc */
    { 0x051d, 0x0002, 2 },  /* apc */
    { 0x051d, 0x0003, 2 },  /* apc */
    { 0x051d, 0x0004, 2 },  /* apc */
    { 0x051d, 0x0005, 2 },  /* apc */
    { 0x2341, 0x0036, 3 },  /* arduino */
    { 0x2341, 0x8036, 3 },  /* arduino */
    { 0x050d, 0x0980, 4 },  /* belkin */
    { 0x050d, 0x0900, 4 },  /* belkin */
    { 0x050d, 0x0910, 4 },  /* belkin */
    { 0x050d, 0x0912, 4 },  /* belkin */
    { 0x050d, 0x0551, 4 },  /* belkin */
    { 0x050d, 0x0750, 4 },  /* belkin */
    { 0x050d, 0x0751, 4 },  /* belkin */
    { 0x050d, 0x0375, 4 },  /* belkin */
    { 0x050d, 0x0f51, 4 },  /* belkin */
    { 0x050d, 0x1100, 4 },  /* belkin */
    { 0x10af, 0x0000, 4 },  /* belkin */
    { 0x10af, 0x0001, 4 },  /* belkin */
    { 0x10af, 0x0002, 4 },  /* belkin */
    { 0x10af, 0x0004, 4 },  /* belkin */
    { 0x10af, 0x0008, 4 },  /* belkin */
    { 0x0764, 0x0005, 5 },  /* cps */
    { 0x0764, 0x0501, 5 },  /* cps */
    { 0x0764, 0x0601, 5 },  /* cps */
    { 0x0483, 0xa430, 5 },  /* cps */
    { 0x05dd, 0x041b, 6 },  /* delta_ups */
    { 0x3746, 0xffff, 7 },  /* ecoflow */
    { 0x0483, 0xa113, 8 },  /* ever */
    { 0x2e51, 0xffff, 8 },  /* ever */
    { 0x2e51, 0x0000, 8 },  /* ever */
    { 0x075d, 0x0300, 9 },  /* idowell */
    { 0x06da, 0xffff, 9 },  /* idowell */
    { 0x06da, 0xffff, 11 },  /* liebert */
    { 0x04d8, 0xd004, 12 },  /* openups */
    { 0x04d8, 0xd005, 12 },  /* openups */
    { 0x0d9f, 0x00a2, 13 },  /* powercom */
    { 0x0d9f, 0x00a3, 13 },  /* powercom */
    { 0x0d9f, 0x00a4, 13 },  /* powercom */
    { 0x0d9f, 0x00a5, 13 },  /* powercom */
    { 0x0d9f, 0x00a6, 13 },  /* powercom */
    { 0x0d9f, 0x0004, 13 },  /* powercom */
    { 0x0d9f, 0x0001, 13 },  /* powercom */
    { 0x4234, 0x0002, 14 },  /* powervar */
    { 0x2e66, 0x0101, 15 },  /* salicru */
    { 0x2e66, 0x0201, 15 },  /* salicru */
    { 0x2e66, 0x0202, 15 },  /* salicru */
    { 0x2e66, 0x0203, 15 },  /* salicru */
    { 0x2e66, 0x0300, 15 },  /* salicru */
    { 0x2e66, 0x0302, 15 },  /* salicru */
    { 0x09ae, 0x1003, 16 },  /* tripplite */
    { 0x09ae, 0x1007, 16 },  /* tripplite */
    { 0x09ae, 0x1008, 16 },  /* tripplite */
    { 0x09ae, 0x1009, 16 },  /* tripplite */
    { 0x09ae, 0x1010, 16 },  /* tripplite */
    { 0x09ae, 0x1330, 16 },  /* tripplite */
    { 0x09ae, 0x2005, 16 },  /* tripplite */
    { 0x09ae, 0x2007, 16 },  /* tripplite */
    { 0x09ae, 0x2008, 16 },  /* tripplite */
    { 0x09ae, 0x2009, 16 },  /* tripplite */
    { 0x09ae, 0x2010, 16 },  /* tripplite */
    { 0x09ae, 0x2011, 16 },  /* tripplite */
    { 0x09ae, 0x2012, 16 },  /* tripplite */
    { 0x09ae, 0x2013, 16 },  /* tripplite */
    { 0x09ae, 0x2014, 16 },  /* tripplite */
    { 0x09ae, 0x3008, 16 },  /* tripplite */
    { 0x09ae, 0x3009, 16 },  /* tripplite */
    { 0x09ae, 0x3010, 16 },  /* tripplite */
    { 0x09ae, 0x3011, 16 },  /* tripplite */
    { 0x09ae, 0x3012, 16 },  /* tripplite */
    { 0x09ae, 0x3013, 16 },  /* tripplite */
    { 0x09ae, 0x3014, 16 },  /* tripplite */
    { 0x09ae, 0x3015, 16 },  /* tripplite */
    { 0x09ae, 0x3016, 16 },  /* tripplite */
    { 0x09ae, 0x3024, 16 },  /* tripplite */
    { 0x09ae, 0x4001, 16 },  /* tripplite */
    { 0x09ae, 0x4002, 16 },  /* tripplite */
    { 0x09ae, 0x4003, 16 },  /* tripplite */
    { 0x09ae, 0x4004, 16 },  /* tripplite */
    { 0x09ae, 0x4005, 16 },  /* tripplite */
    { 0x09ae, 0x4006, 16 },  /* tripplite */
    { 0x09ae, 0x4007, 16 },  /* tripplite */
    { 0x09ae, 0x4008, 16 },  /* tripplite */
    { 0x03f0, 0x0001, 16 },  /* tripplite */
    { 0x03f0, 0x1fe0, 16 },  /* tripplite */
    { 0x03f0, 0x1fe1, 16 },  /* tripplite */
    { 0x03f0, 0x1fe2, 16 },  /* tripplite */
    { 0x03f0, 0x1fe3, 16 },  /* tripplite */
    { 0x03f0, 0x1f06, 16 },  /* tripplite */
    { 0x03f0, 0x1f08, 16 },  /* tripplite */
    { 0x03f0, 0x1f09, 16 },  /* tripplite */
    { 0x03f0, 0x1f0a, 16 },  /* tripplite */
    { 0x05dd, 0xa011, 16 },  /* tripplite */
    { 0x05dd, 0xa0a0, 16 },  /* tripplite */
};
const size_t ups_vartab_id_count = sizeof(ups_vartab_ids) / sizeof(ups_vartab_ids[0]);

const uint16_t *ups_vartab_list(int sub, size_t *len)
{
    if (sub < 0 || sub >= (int)(sizeof(s_lists) / sizeof(s_lists[0]))) {
        *len = 67;
        return s_common;
    }
    *len = s_list_len[sub];
    return s_lists[sub];
}

/* NUT's status lookups: value -> token (ups_nutstatus.h), set or clear. */
static const ups_st_lkp_t s_lk_apc_linefailcause_frange_info[] = { { 7, 29, 0 }, { 0, 29, 1 } };
static const ups_st_lkp_t s_lk_apc_linefailcause_vrange_info[] = { { 1, 28, 0 }, { 2, 28, 0 }, { 4, 28, 0 }, { 8, 28, 0 }, { 9, 28, 0 }, { 0, 28, 1 } };
static const ups_st_lkp_t s_lk_apcstatusflag_info[] = { { 8, 14, 1 }, { 16, 14, 1 }, { 0, 14, 0 } };
static const ups_st_lkp_t s_lk_awaitingpower_info[] = { { 1, 22, 0 }, { 0, 22, 1 } };
static const ups_st_lkp_t s_lk_battvolthi_info[] = { { 1, 26, 0 }, { 0, 26, 1 } };
static const ups_st_lkp_t s_lk_battvoltlo_info[] = { { 1, 25, 0 }, { 0, 25, 1 } };
static const ups_st_lkp_t s_lk_boost_info[] = { { 1, 9, 0 }, { 0, 9, 1 } };
static const ups_st_lkp_t s_lk_bypass_auto_info[] = { { 1, 10, 0 }, { 0, 10, 1 } };
static const ups_st_lkp_t s_lk_bypass_manual_info[] = { { 1, 11, 0 }, { 0, 11, 1 } };
static const ups_st_lkp_t s_lk_chargerfail_info[] = { { 1, 27, 0 }, { 0, 27, 1 } };
static const ups_st_lkp_t s_lk_charging_info[] = { { 1, 3, 0 }, { 0, 3, 1 } };
static const ups_st_lkp_t s_lk_commfault_info[] = { { 1, 17, 0 }, { 0, 17, 1 } };
static const ups_st_lkp_t s_lk_depleted_info[] = { { 1, 18, 0 }, { 0, 18, 1 } };
static const ups_st_lkp_t s_lk_discharging_info[] = { { 1, 2, 0 }, { 0, 2, 1 } };
static const ups_st_lkp_t s_lk_fanfail_info[] = { { 1, 23, 0 }, { 0, 23, 1 } };
static const ups_st_lkp_t s_lk_frange_info[] = { { 0, 29, 1 }, { 1, 29, 0 } };
static const ups_st_lkp_t s_lk_fullycharged_info[] = { { 1, 20, 0 }, { 0, 21, 0 } };
static const ups_st_lkp_t s_lk_lowbatt_info[] = { { 1, 4, 0 }, { 0, 4, 1 } };
static const ups_st_lkp_t s_lk_mge_onbatt_info[] = { { 1, 0, 1 }, { 0, 0, 0 } };
static const ups_st_lkp_t s_lk_nobattery_info[] = { { 1, 24, 1 }, { 0, 24, 0 } };
static const ups_st_lkp_t s_lk_off_info[] = { { 0, 14, 0 }, { 1, 14, 1 } };
static const ups_st_lkp_t s_lk_online_info[] = { { 1, 0, 0 }, { 0, 1, 0 } };
static const ups_st_lkp_t s_lk_overheat_info[] = { { 1, 16, 0 }, { 0, 16, 1 } };
static const ups_st_lkp_t s_lk_overload_info[] = { { 1, 5, 0 }, { 0, 5, 1 } };
static const ups_st_lkp_t s_lk_replacebatt_info[] = { { 1, 6, 0 }, { 0, 6, 1 } };
static const ups_st_lkp_t s_lk_shutdownimm_info[] = { { 1, 7, 0 }, { 0, 7, 1 } };
static const ups_st_lkp_t s_lk_timelimitexpired_info[] = { { 1, 19, 0 }, { 0, 19, 1 } };
static const ups_st_lkp_t s_lk_trim_info[] = { { 1, 8, 0 }, { 0, 8, 1 } };
static const ups_st_lkp_t s_lk_vrange_info[] = { { 0, 28, 1 }, { 1, 28, 0 } };

const ups_st_row_t ups_st_rows[77] = {
    { s_lk_online_info, 2, 4, { 0x00840004, 0x00840024, 0x00840002, 0x008500d0 } },  /* online_info */
    { s_lk_mge_onbatt_info, 2, 6, { 0x00840004, 0x00840016, 0x0084001a, 0x00ff0003, 0x00840002, 0x0084006d } },  /* mge_onbatt_info */
    { s_lk_lowbatt_info, 2, 4, { 0x00840004, 0x00840024, 0x00840002, 0x00850042 } },  /* lowbatt_info */
    { s_lk_overload_info, 2, 7, { 0x00840004, 0x00840016, 0x0084001c, 0x00840065, 0x00ff0001, 0x00840002, 0xffff007e } },  /* overload_info */
    { s_lk_overload_info, 2, 7, { 0x00840004, 0x00840016, 0x0084001c, 0x00840065, 0x00ff0002, 0x00840002, 0xffff007e } },  /* overload_info */
    { s_lk_overload_info, 2, 4, { 0x00840004, 0x00840024, 0x00840002, 0x00840065 } },  /* overload_info */
    { s_lk_replacebatt_info, 2, 4, { 0x00840004, 0x00840024, 0x00840002, 0x0085004b } },  /* replacebatt_info */
    { s_lk_replacebatt_info, 2, 6, { 0x00840004, 0xffff0018, 0xffff001a, 0x00ff0002, 0x00840002, 0xffff0093 } },  /* replacebatt_info */
    { s_lk_trim_info, 2, 6, { 0x00840004, 0x00840016, 0x0084001a, 0x00ff0001, 0x00840002, 0x0084006f } },  /* trim_info */
    { s_lk_boost_info, 2, 6, { 0x00840004, 0x00840016, 0x0084001a, 0x00ff0001, 0x00840002, 0x0084006e } },  /* boost_info */
    { s_lk_vrange_info, 2, 6, { 0x00840004, 0x00840016, 0x0084001a, 0x00ff0001, 0x00840002, 0x00840063 } },  /* vrange_info */
    { s_lk_frange_info, 2, 6, { 0x00840004, 0x00840016, 0x0084001a, 0x00ff0001, 0x00840002, 0x00840064 } },  /* frange_info */
    { s_lk_off_info, 2, 4, { 0x00840004, 0x00840024, 0x00840002, 0x00840061 } },  /* off_info */
    { s_lk_bypass_auto_info, 2, 6, { 0x00840004, 0x00840016, 0x0084001a, 0x00ff0002, 0x00840002, 0x0084006d } },  /* bypass_auto_info */
    { s_lk_bypass_manual_info, 2, 6, { 0x00840004, 0x00840016, 0x0084001a, 0x00ff0004, 0x00840002, 0x0084006d } },  /* bypass_manual_info */
    { s_lk_fanfail_info, 2, 4, { 0x00840004, 0x00840024, 0x00840002, 0xffff0077 } },  /* fanfail_info */
    { s_lk_nobattery_info, 2, 5, { 0x00840004, 0x00840010, 0x00840012, 0x00840002, 0x00840060 } },  /* nobattery_info */
    { s_lk_chargerfail_info, 2, 5, { 0x00840004, 0x00840010, 0x00840014, 0x00840002, 0x00840062 } },  /* chargerfail_info */
    { s_lk_battvolthi_info, 2, 5, { 0x00840004, 0x00840010, 0x00840014, 0x00840002, 0xffff0074 } },  /* battvolthi_info */
    { s_lk_battvolthi_info, 2, 6, { 0x00840004, 0x00840016, 0x0084001a, 0x00ff0001, 0x00840002, 0xffff0074 } },  /* battvolthi_info */
    { s_lk_battvolthi_info, 2, 5, { 0x00840004, 0x00840010, 0x00840012, 0x00840002, 0xffff0074 } },  /* battvolthi_info */
    { s_lk_battvoltlo_info, 2, 5, { 0x00840004, 0x00840010, 0x00840014, 0x00840002, 0xffff0075 } },  /* battvoltlo_info */
    { s_lk_mge_onbatt_info, 2, 6, { 0x00840004, 0x00840016, 0x0084001a, 0x00ff0001, 0x00840002, 0xffff0075 } },  /* mge_onbatt_info */
    { s_lk_commfault_info, 2, 4, { 0x00840004, 0x00840024, 0x00840002, 0x00840062 } },  /* commfault_info */
    { s_lk_overheat_info, 2, 4, { 0x00840004, 0x00840024, 0x00840002, 0x00840067 } },  /* overheat_info */
    { s_lk_shutdownimm_info, 2, 4, { 0x00840004, 0x00840024, 0x00840002, 0x00840069 } },  /* shutdownimm_info */
    { s_lk_discharging_info, 2, 4, { 0x00840004, 0x00840024, 0x00840002, 0x00850045 } },  /* discharging_info */
    { s_lk_charging_info, 2, 4, { 0x00840004, 0x00840024, 0x00840002, 0x00850044 } },  /* charging_info */
    { s_lk_timelimitexpired_info, 2, 4, { 0x00840004, 0x00840024, 0x00840002, 0x00850043 } },  /* timelimitexpired_info */
    { s_lk_nobattery_info, 2, 4, { 0x00840004, 0x00840024, 0x00840002, 0x008500d1 } },  /* nobattery_info */
    { s_lk_charging_info, 2, 3, { 0x00840004, 0x00840024, 0x00850044 } },  /* charging_info */
    { s_lk_discharging_info, 2, 3, { 0x00840004, 0x00840024, 0x00850045 } },  /* discharging_info */
    { s_lk_online_info, 2, 3, { 0x00840004, 0x00840024, 0x008500d0 } },  /* online_info */
    { s_lk_lowbatt_info, 2, 3, { 0x00840004, 0x00840024, 0x00850042 } },  /* lowbatt_info */
    { s_lk_shutdownimm_info, 2, 3, { 0x00840004, 0x00840024, 0x00840069 } },  /* shutdownimm_info */
    { s_lk_apcstatusflag_info, 3, 3, { 0x00840004, 0x00840024, 0xff860060 } },  /* apcstatusflag_info */
    { s_lk_apc_linefailcause_vrange_info, 6, 3, { 0x00840004, 0x0084001a, 0xff860052 } },  /* apc_linefailcause_vrange_info */
    { s_lk_apc_linefailcause_frange_info, 2, 3, { 0x00840004, 0x0084001a, 0xff860052 } },  /* apc_linefailcause_frange_info */
    { s_lk_fullycharged_info, 2, 4, { 0x00840004, 0x00840024, 0x00840002, 0x00850046 } },  /* fullycharged_info */
    { s_lk_depleted_info, 2, 4, { 0x00840004, 0x00840024, 0x00840002, 0x00850047 } },  /* depleted_info */
    { s_lk_boost_info, 2, 3, { 0x00840004, 0x0084001c, 0x0084006e } },  /* boost_info */
    { s_lk_overload_info, 2, 3, { 0x00840004, 0x0084001c, 0x00840065 } },  /* overload_info */
    { s_lk_vrange_info, 2, 4, { 0x00840004, 0x00840016, 0x00840002, 0x00840063 } },  /* vrange_info */
    { s_lk_trim_info, 2, 4, { 0x00840004, 0x00840016, 0x00840002, 0x0084006f } },  /* trim_info */
    { s_lk_boost_info, 2, 4, { 0x00840004, 0x00840016, 0x00840002, 0x0084006e } },  /* boost_info */
    { s_lk_overload_info, 2, 4, { 0x00840004, 0x00840016, 0x00840002, 0x00840065 } },  /* overload_info */
    { s_lk_nobattery_info, 2, 4, { 0x00840004, 0x00840016, 0x00840002, 0x0084006d } },  /* nobattery_info */
    { s_lk_overheat_info, 2, 4, { 0x00840004, 0x00840016, 0x00840002, 0x00840067 } },  /* overheat_info */
    { s_lk_commfault_info, 2, 4, { 0x00840004, 0x00840016, 0x00840002, 0x00840062 } },  /* commfault_info */
    { s_lk_awaitingpower_info, 2, 4, { 0x00840004, 0x00840016, 0x00840002, 0x00840072 } },  /* awaitingpower_info */
    { s_lk_commfault_info, 2, 4, { 0x00840004, 0x00840024, 0x00840002, 0x00840073 } },  /* commfault_info */
    { s_lk_awaitingpower_info, 2, 4, { 0x00840004, 0x00840024, 0x00840002, 0x00840072 } },  /* awaitingpower_info */
    { s_lk_overload_info, 2, 4, { 0x00840004, 0x00000000, 0xff000016, 0xff000017 } },  /* overload_info */
    { s_lk_lowbatt_info, 2, 4, { 0x00840004, 0x00000000, 0xff000016, 0xff000018 } },  /* lowbatt_info */
    { s_lk_boost_info, 2, 4, { 0x00840004, 0x00000000, 0xff000016, 0xff000019 } },  /* boost_info */
    { s_lk_trim_info, 2, 4, { 0x00840004, 0x00000000, 0xff000016, 0xff00001a } },  /* trim_info */
    { s_lk_charging_info, 2, 4, { 0x00840004, 0x00000000, 0xff000016, 0xff00001d } },  /* charging_info */
    { s_lk_replacebatt_info, 2, 4, { 0x00840004, 0x00000000, 0xff000016, 0xff000020 } },  /* replacebatt_info */
    { s_lk_overload_info, 2, 4, { 0x00840004, 0x00000000, 0xff000030, 0xff000031 } },  /* overload_info */
    { s_lk_commfault_info, 2, 4, { 0x00840004, 0x00000000, 0xff000030, 0xff000038 } },  /* commfault_info */
    { s_lk_online_info, 2, 3, { 0x00840004, 0x00840002, 0x008500d0 } },  /* online_info */
    { s_lk_nobattery_info, 2, 3, { 0x00840004, 0x00840002, 0x008500d1 } },  /* nobattery_info */
    { s_lk_lowbatt_info, 2, 3, { 0x00840004, 0x00840002, 0x00850042 } },  /* lowbatt_info */
    { s_lk_boost_info, 2, 3, { 0x00840004, 0x00840002, 0x0084006e } },  /* boost_info */
    { s_lk_trim_info, 2, 3, { 0x00840004, 0x00840002, 0x0084006f } },  /* trim_info */
    { s_lk_charging_info, 2, 3, { 0x00840004, 0x00840002, 0x00850044 } },  /* charging_info */
    { s_lk_commfault_info, 2, 3, { 0x00840004, 0x00840002, 0x00840073 } },  /* commfault_info */
    { s_lk_discharging_info, 2, 3, { 0x00840004, 0x00840002, 0x00850045 } },  /* discharging_info */
    { s_lk_replacebatt_info, 2, 3, { 0x00840004, 0x00840002, 0x0085004b } },  /* replacebatt_info */
    { s_lk_overload_info, 2, 3, { 0x00840004, 0x00840002, 0x00840065 } },  /* overload_info */
    { s_lk_timelimitexpired_info, 2, 3, { 0x00840004, 0x00840002, 0x00850043 } },  /* timelimitexpired_info */
    { s_lk_shutdownimm_info, 2, 3, { 0x00840004, 0x00840002, 0x00840069 } },  /* shutdownimm_info */
    { s_lk_commfault_info, 2, 3, { 0x00840004, 0x0084001c, 0x00840073 } },  /* commfault_info */
    { s_lk_online_info, 2, 4, { 0x00840004, 0x00840024, 0x00840002, 0x008400d0 } },  /* online_info */
    { s_lk_discharging_info, 2, 4, { 0x00840004, 0x00840024, 0x00840002, 0x00840045 } },  /* discharging_info */
    { s_lk_charging_info, 2, 4, { 0x00840004, 0x00840024, 0x00840002, 0x00840044 } },  /* charging_info */
    { s_lk_replacebatt_info, 2, 4, { 0x00840004, 0x00840024, 0x00840002, 0x0084004b } },  /* replacebatt_info */
};
static const uint16_t s_st_explore[] = { 0 };
static const uint16_t s_st_mge[] = { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25 };
static const uint16_t s_st_apc[] = { 0, 26, 27, 25, 2, 5, 6, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37 };
static const uint16_t s_st_arduino[] = { 0, 26, 27, 6, 25, 2, 5, 28, 29, 38, 39 };
static const uint16_t s_st_belkin[] = { 0 };
static const uint16_t s_st_cps[] = { 0, 27, 26, 2, 38, 28, 6, 40, 41 };
static const uint16_t s_st_delta_ups[] = { 12, 23, 25, 0, 2, 38, 27, 26, 39, 6, 42, 43, 44, 45, 46, 47, 48, 49 };
static const uint16_t s_st_ecoflow[] = { 0, 29, 2, 50, 27, 26, 38, 39, 6, 5, 28, 25 };
static const uint16_t s_st_ever[] = { 0, 51, 29, 50, 26, 6, 5, 24, 25, 52, 53, 54, 55, 56, 57, 58, 59 };
static const uint16_t s_st_idowell[] = { 0, 29, 2, 27, 50, 26, 12, 23, 6, 5, 25 };
static const uint16_t s_st_legrand[] = { 0, 2, 27, 26, 41 };
static const uint16_t s_st_liebert[] = { 0, 2, 27, 26, 5, 12, 23, 25, 8, 9 };
static const uint16_t s_st_openups[] = { 23, 5, 24, 25, 2, 28, 6, 29 };
static const uint16_t s_st_powercom[] = { 0, 29, 2, 27, 50, 26, 6, 5, 28, 25, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71 };
static const uint16_t s_st_powervar[] = { 0, 26, 27, 25, 2, 5, 6, 28, 24, 38, 39 };
static const uint16_t s_st_salicru[] = { 0, 27, 26, 2, 38, 28, 72, 40, 41, 5, 24 };
static const uint16_t s_st_tripplite[] = { 23, 25, 0, 2, 38, 27, 26, 39, 6, 73, 74, 75, 76, 42, 43, 44, 45, 47, 48, 49 };
static const uint16_t s_st_common[] = { 0, 2, 5, 6, 8, 9, 12, 23, 24, 25, 26, 27, 28, 29, 38, 39, 40, 41, 42, 43, 44, 45, 47, 48, 49, 50 };
static const uint16_t *const s_st_lists[] = {
    s_st_explore,
    s_st_mge,
    s_st_apc,
    s_st_arduino,
    s_st_belkin,
    s_st_cps,
    s_st_delta_ups,
    s_st_ecoflow,
    s_st_ever,
    s_st_idowell,
    s_st_legrand,
    s_st_liebert,
    s_st_openups,
    s_st_powercom,
    s_st_powervar,
    s_st_salicru,
    s_st_tripplite,
};
static const uint16_t s_st_len[] = {
    0,
    26,
    17,
    11,
    0,
    9,
    18,
    12,
    17,
    11,
    5,
    10,
    8,
    22,
    11,
    11,
    20,
};
const uint16_t *ups_st_list(int sub, size_t *len)
{
    if (sub < 0 || sub >= (int)(sizeof(s_st_lists) / sizeof(s_st_lists[0]))) {
        *len = 26;
        return s_st_common;
    }
    *len = s_st_len[sub];
    return s_st_lists[sub];
}

/* Vendor-page usages a row reads, sorted, for hid_parser's keep test. */
const uint32_t ups_vartab_vendor_usages[85] = {
    0xff000017, 0xff000018, 0xff000019, 0xff00001a, 0xff00001d, 0xff000020,
    0xff000031, 0xff000038, 0xff000040, 0xff000041, 0xff000042, 0xff000044,
    0xff000045, 0xff000046, 0xff000051, 0xff000052, 0xff000053, 0xff000054,
    0xff000060, 0xff000066, 0xff000067, 0xff000068, 0xff000069, 0xff00006a,
    0xff00006b, 0xff00006c, 0xff00006d, 0xff00006e, 0xff00006f, 0xff000070,
    0xff000071, 0xff000072, 0xff000081, 0xff000082, 0xff000083, 0xff000084,
    0xff000085, 0xff000086, 0xff00008b, 0xff0100d0, 0xff860052, 0xff860060,
    0xff86007c, 0xff86007d, 0xff86007e, 0xffff0043, 0xffff0044, 0xffff0045,
    0xffff0046, 0xffff0047, 0xffff0049, 0xffff004b, 0xffff004d, 0xffff004e,
    0xffff0050, 0xffff0051, 0xffff0052, 0xffff0053, 0xffff0056, 0xffff0057,
    0xffff0058, 0xffff0059, 0xffff005a, 0xffff005b, 0xffff005c, 0xffff005d,
    0xffff005e, 0xffff005f, 0xffff0069, 0xffff0074, 0xffff0075, 0xffff0077,
    0xffff007c, 0xffff007e, 0xffff007f, 0xffff0081, 0xffff0086, 0xffff0092,
    0xffff0093, 0xffff0097, 0xffff009c, 0xffff00ba, 0xffff00f1, 0xffff00f8,
    0xffff00f9,
};
const size_t ups_vartab_vendor_usage_count = 85;
